export const ACHIEVEMENT_NAMES = {
  collect50Hydrogen: {
    en: "Collect 50 Hydrogen",
    es: "Recoge 50 HidrÃ³geno",
    pt: "Colete 50 de HidrogÃªnio",
    de: "Sammle 50 Wasserstoff",
    it: "Raccogli 50 Idrogeno",
    fr: "Collectez 50 HydrogÃ¨ne",
  },
  collect1000Hydrogen: {
    en: "Gather 1000 Hydrogen",
    es: "ReÃºne 1000 HidrÃ³geno",
    pt: "Colete 1000 de HidrogÃªnio",
    de: "Sammle 1000 Wasserstoff",
    it: "Raccogli 1000 Idrogeno",
    fr: "Rassemblez 1000 HydrogÃ¨ne",
  },
  collect5000Carbon: {
    en: "Accumulate 5000 Carbon",
    es: "Acumula 5000 Carbono",
    pt: "Acumule 5000 de Carbono",
    de: "Sammle 5000 Kohlenstoff",
    it: "Accumula 5000 Carbonio",
    fr: "Accumulez 5000 Carbone",
  },
  collect50000Iron: {
    en: "Collect 50000 Iron",
    es: "Recoge 50000 Hierro",
    pt: "Colete 50000 de Ferro",
    de: "Sammle 50000 Eisen",
    it: "Raccogli 50000 Ferro",
    fr: "Collectez 50000 Fer",
  },
  collect100Precipitation: {
    en: "Collect 100 Precipitation",
    es: "Recoge 100 PrecipitaciÃ³n",
    pt: "Colete 100 de PrecipitaÃ§Ã£o",
    de: "Sammle 100 Niederschlag",
    it: "Raccogli 100 Precipitazione",
    fr: "Collectez 100 PrÃ©cipitation",
  },
  fuseElement: {
    en: "Fuse an Element",
    es: "Fusiona un Elemento",
    pt: "Funda um Elemento",
    de: "Fusioniere ein Element",
    it: "Fondi un Elemento",
    fr: "Fusionnez un Ã‰lÃ©ment",
  },
  createSteel: {
    en: "Create Steel",
    es: "Crea Acero",
    pt: "Crie AÃ§o",
    de: "Erstelle Stahl",
    it: "Crea Acciaio",
    fr: "CrÃ©ez de l\u0027Acier",
  },
  createTitanium: {
    en: "Create Titanium",
    es: "Crea Titanio",
    pt: "Crie TitÃ¢nio",
    de: "Erstelle Titan",
    it: "Crea Titanio",
    fr: "CrÃ©ez du Titane",
  },
  unlockCompounds: {
    en: "Unlock Compounds",
    es: "Desbloquea Compuestos",
    pt: "Desbloqueie Compostos",
    de: "Schalte Verbindungen frei",
    it: "Sblocca Composti",
    fr: "DÃ©bloquez des ComposÃ©s",
  },
  researchTechnology: {
    en: "Research a Technology",
    es: "Investiga una TecnologÃ­a",
    pt: "Pesquise uma Tecnologia",
    de: "Erforsche eine Technologie",
    it: "Ricerca una Tecnologia",
    fr: "Recherchez une Technologie",
  },
  researchAllTechnologies: {
    en: "Research all Technologies",
    es: "Investiga todas las TecnologÃ­as",
    pt: "Pesquise todas as Tecnologias",
    de: "Erforsche alle Technologien",
    it: "Ricerca tutte le Tecnologie",
    fr: "Recherchez toutes les Technologies",
  },
  achieve100FusionEfficiency: {
    en: "Achieve 100% Fusion Efficiency",
    es: "Logra 100% de Eficiencia de FusiÃ³n",
    pt: "Alcance 100% de EficiÃªncia de FusÃ£o",
    de: "Erreiche 100% Fusionseffizienz",
    it: "Raggiungi 100% Efficienza di Fusione",
    fr: "Atteignez 100% d\u0027EfficacitÃ© de Fusion",
  },
  have50HoursWithOnePioneer: {
    en: "Log 50 Active Hours with One Pioneer",
    es: "Registra 50 Horas Activas con un Pionero",
    pt: "Tenha 50 Horas com um Pioneiro",
    de: "Protokolliere 50 aktive Stunden mit einem Pionier",
    it: "Registra 50 Ore Attive con un Pioniere",
    fr: "Enregistrez 50 Heures Actives avec un Pionnier",
  },
  buildPowerPlant: {
    en: "Build a Power Plant",
    es: "Construye una Planta de EnergÃ­a",
    pt: "Construa uma Usina de Energia",
    de: "Baue ein Kraftwerk",
    it: "Costruisci una Centrale Elettrica",
    fr: "Construisez une Centrale Ã‰lectrique",
  },
  buildSolarPowerPlant: {
    en: "Construct a Solar Power Plant",
    es: "Construye una Planta Solar",
    pt: "Construa uma Usina Solar",
    de: "Baue ein Solarkraftwerk",
    it: "Costruisci una Centrale Solare",
    fr: "Construisez une Centrale Solaire",
  },
  collect100TitaniumAsPrecipitation: {
    en: "Collect 100 Titanium as Precipitation",
    es: "Recoge 100 Titanio como PrecipitaciÃ³n",
    pt: "Colete 100 de TitÃ¢nio como PrecipitaÃ§Ã£o",
    de: "Sammle 100 Titan als Niederschlag",
    it: "Raccogli 100 Titanio come Precipitazione",
    fr: "Collectez 100 Titane comme PrÃ©cipitation",
  },
  gain100Cash: {
    en: "Gain 100 Cash",
    es: "Gana 100 Efectivo",
    pt: "Ganhe 100 em Dinheiro",
    de: "Erhalte 100 Bargeld",
    it: "Ottieni 100 Contanti",
    fr: "Gagnez 100 EspÃ¨ces",
  },
  gain10000Cash: {
    en: "Gain 10K Cash",
    es: "Gana 10K Efectivo",
    pt: "Ganhe 10K em Dinheiro",
    de: "Erhalte 10K Bargeld",
    it: "Ottieni 10K Contanti",
    fr: "Gagnez 10K EspÃ¨ces",
  },
  gain100000Cash: {
    en: "Gain 100K Cash",
    es: "Gana 100K Efectivo",
    pt: "Ganhe 100K em Dinheiro",
    de: "Erhalte 100K Bargeld",
    it: "Ottieni 100K Contanti",
    fr: "Gagnez 100K EspÃ¨ces",
  },
  gain1000000Cash: {
    en: "Gain 1M Cash",
    es: "Gana 1M Efectivo",
    pt: "Ganhe 1M em Dinheiro",
    de: "Erhalte 1M Bargeld",
    it: "Ottieni 1M Contanti",
    fr: "Gagnez 1M EspÃ¨ces",
  },
  seeAllNewsTickers: {
    en: "See All News Tickers",
    es: "Ve todos los Ticker de Noticias",
    pt: "Veja todas as Faixas de NotÃ­cias",
    de: "Sehe alle Nachrichten-Ticker",
    it: "Vedi tutti i Ticker di Notizie",
    fr: "Voyez tous les Ticker d\u0027ActualitÃ©s",
  },
  activateAllWackyNewsTickers: {
    en: "Activate All Wacky News Tickers",
    es: "Activa todos los Ticker de Noticias Locas",
    pt: "Ative todas as Faixas de NotÃ­cias Malucas",
    de: "Aktiviere alle verrÃ¼ckten Nachrichten-Ticker",
    it: "Attiva tutti i Ticker di Notizie Pazze",
    fr: "Activez tous les Ticker d\u0027ActualitÃ©s Loufoques",
  },
  discoverLegendaryAsteroid: {
    en: "Discover a Legendary Asteroid",
    es: "Descubre un Asteroide Legendario",
    pt: "Descubra um Asteroide LendÃ¡rio",
    de: "Entdecke einen legendÃ¤ren Asteroiden",
    it: "Scopri un Asteroide Leggendario",
    fr: "DÃ©couvrez un AstÃ©roÃ¯de LÃ©gendaire",
  },
  have4RocketsMiningAntimatter: {
    en: "Have 4 Rockets Mining Antimatter",
    es: "Ten 4 Cohetes Minando Antimateria",
    pt: "Tenha 4 Foguetes Minerando AntimatÃ©ria",
    de: "Habe 4 Raketen, die Antimaterie abbauen",
    it: "Avere 4 Razzi che Estraggono Antimateria",
    fr: "Ayez 4 FusÃ©es Minant de l\u0027AntimatiÃ¨re",
  },
  tripPower: {
    en: "Trip the Power",
    es: "Corta la EnergÃ­a",
    pt: "Desligue a Energia",
    de: "Stromausfall auslÃ¶sen",
    it: "Disattiva l\u0027Energia",
    fr: "DÃ©clenchez une Panne de Courant",
  },
  discoverAsteroid: {
    en: "Discover an Asteroid",
    es: "Descubre un Asteroide",
    pt: "Descubra um Asteroide",
    de: "Entdecke einen Asteroiden",
    it: "Scopri un Asteroide",
    fr: "DÃ©couvrez un AstÃ©roÃ¯de",
  },
  launchRocket: {
    en: "Launch a Rocket",
    es: "Lanza un Cohete",
    pt: "Lance um Foguete",
    de: "Starte eine Rakete",
    it: "Lancia un Razzo",
    fr: "Lancez une FusÃ©e",
  },
  mineAllAntimatterAsteroid: {
    en: "Mine all Antimatter from an Asteroid",
    es: "Mina todo el Antimaterio de un Asteroide",
    pt: "Extraia toda a AntimatÃ©ria de um Asteroide",
    de: "Bergbaue alle Antimaterie von einem Asteroiden",
    it: "Estrai tutta l\u0027Antimateria da un Asteroide",
    fr: "Minez toute l\u0027AntimatiÃ¨re d\u0027un AstÃ©roÃ¯de",
  },
  studyStar: {
    en: "Study a Star",
    es: "Estudia una Estrella",
    pt: "Estude uma Estrela",
    de: "Studiere einen Stern",
    it: "Studia una Stella",
    fr: "Ã‰tudiez une Ã‰toile",
  },
  studyStarMoreThan5LYAway: {
    en: "Study a Star over 5 light-years away",
    es: "Estudia una Estrella a mÃ¡s de 5 aÃ±os luz de distancia",
    pt: "Estude uma Estrela a mais de 5 anos-luz de distÃ¢ncia",
    de: "Studiere einen Stern Ã¼ber 5 Lichtjahre entfernt",
    it: "Studia una Stella a piÃ¹ di 5 anni luce di distanza",
    fr: "Ã‰tudiez une Ã‰toile Ã  plus de 5 annÃ©es-lumiÃ¨re",
  },
  studyStarMoreThan20LYAway: {
    en: "Study a Star over 20 light-years away",
    es: "Estudia una Estrella a mÃ¡s de 20 aÃ±os luz de distancia",
    pt: "Estude uma Estrela a mais de 20 anos-luz de distÃ¢ncia",
    de: "Studiere einen Stern Ã¼ber 20 Lichtjahre entfernt",
    it: "Studia una Stella a piÃ¹ di 20 anni luce di distanza",
    fr: "Ã‰tudiez une Ã‰toile Ã  plus de 20 annÃ©es-lumiÃ¨re",
  },
  launchStarship: {
    en: "Launch a Starship",
    es: "Lanza una Nave Estelar",
    pt: "Lance uma Nave Estelar",
    de: "Starte ein Raumschiff",
    it: "Lancia un\u0027Astronave",
    fr: "Lancez un Vaisseau Spatial",
  },
  performGalacticMarketTransaction: {
    en: "Perform a Galactic Market Transaction",
    es: "Realiza una TransacciÃ³n en el Mercado GalÃ¡ctico",
    pt: "Realize uma TransaÃ§Ã£o no Mercado GalÃ¡ctico",
    de: "FÃ¼hre eine Galaktische Markt-Transaktion durch",
    it: "Esegui una Transazione sul Mercato Galattico",
    fr: "Effectuez une Transaction sur le MarchÃ© Galactique",
  },
  trade10APForCash: {
    en: "Trade 10 AP for Cash",
    es: "Intercambia 10 PA por Efectivo",
    pt: "Troque 10 AP por Dinheiro",
    de: "Tausche 10 AP gegen Bargeld",
    it: "Scambia 10 PA per Contanti",
    fr: "Ã‰changez 10 PA contre des EspÃ¨ces",
  },
  initiateDiplomacyWithAlienRace: {
    en: "Initiate Diplomacy with an Alien Race",
    es: "Inicia Diplomacia con una Raza Alien",
    pt: "Inicie Diplomacia com uma RaÃ§a AlienÃ­gena",
    de: "Initiiere Diplomatie mit einer Alien-Rasse",
    it: "Inizia la Diplomazia con una Razza Aliena",
    fr: "Initiez la Diplomatie avec une Race Alienne",
  },
  bullyEnemyIntoSubmission: {
    en: "Bully an Enemy into Submission",
    es: "Intimida a un Enemigo hasta la SumisiÃ³n",
    pt: "Intimide um Inimigo atÃ© a SubmissÃ£o",
    de: "DrÃ¤nge einen Feind zur Unterwerfung",
    it: "Intimidisci un Nemico fino alla Sottomissione",
    fr: "Intimidez un Ennemi jusqu\u0027Ã  la Soumission",
  },
  vassalizeEnemy: {
    en: "Vassalize an Enemy",
    es: "Vasalliza a un Enemigo",
    pt: "Vassalize um Inimigo",
    de: "Mache einen Feind zu einem Vasallen",
    it: "Vassallizza un Nemico",
    fr: "Vassalisez un Ennemi",
  },
  conquerEnemy: {
    en: "Conquer an Enemy",
    es: "Conquista a un Enemigo",
    pt: "Conquiste um Inimigo",
    de: "Erobere einen Feind",
    it: "Conquista un Nemico",
    fr: "ConquÃ©rez un Ennemi",
  },
  conquerHiveMindEnemy: {
    en: "Defeat a Hive Mind Enemy",
    es: "Derrota a un Enemigo Mente Colmena",
    pt: "Derrote um Inimigo Mente-Colmeia",
    de: "Besiege einen Hive-Mind-Feind",
    it: "Sconfiggi un Nemico Mente Alveare",
    fr: "Vainquez un Ennemi Esprit de Ruche",
  },
  conquerBelligerentEnemy: {
    en: "Defeat a Belligerent Enemy",
    es: "Derrota a un Enemigo Beligerante",
    pt: "Derrote um Inimigo Beligerante",
    de: "Besiege einen Kriegstreitenden Feind",
    it: "Sconfiggi un Nemico Bellicoso",
    fr: "Vainquez un Ennemi Belliqueux",
  },
  conquerEnemyWithoutScanning: {
    en: "Conquer an Enemy without Scanning",
    es: "Conquista a un Enemigo sin Escanear",
    pt: "Conquiste um Inimigo sem EscaneÃ¡-lo",
    de: "Erobere einen Feind ohne Scannen",
    it: "Conquista un Nemico senza Scansionare",
    fr: "ConquÃ©rez un Ennemi sans Scanner",
  },
  settleUnoccupiedSystem: {
    en: "Settle a System with Unsentient Lifeforms",
    es: "Asienta un Sistema con Formas de Vida No Conscientes",
    pt: "Colonize um Sistema com Formas de Vida NÃ£o Sencientes",
    de: "Besiedele ein System mit Unbewussten Lebensformen",
    it: "Insediali in un Sistema con Forme di Vita Non Senzienti",
    fr: "Colonisez un SystÃ¨me avec des Formes de Vie Non Sensibles",
  },
  discoverSystemWithNoLife: {
    en: "Discover a System with No Life at all",
    es: "Descubre un Sistema sin Vida en absoluto",
    pt: "Descubra um Sistema sem Vida",
    de: "Entdecke ein System ohne jegliches Leben",
    it: "Scopri un Sistema senza alcuna Vita",
    fr: "DÃ©couvrez un SystÃ¨me sans aucune Vie",
  },
  settleSystem: {
    en: "Settle a New System",
    es: "Asienta un Nuevo Sistema",
    pt: "Colonize um Novo Sistema",
    de: "Besiedele ein neues System",
    it: "Insediali in un Nuovo Sistema",
    fr: "Colonisez un Nouveau SystÃ¨me",
  },
  spendAP: {
    en: "Spend Ascendency Points (AP)",
    es: "Gasta Puntos de Ascendencia (AP)",
    pt: "Gaste Pontos de AscendÃªncia (AP)",
    de: "Gibt Aufstiegspunkte (AP) aus",
    it: "Spendi Punti Ascendenza (AP)",
    fr: "DÃ©pensez des Points d\u0027Ascendance (AP)",
  },
  liquidateAllAssets: {
    en: "Liquidate All Assets",
    es: "Liquida todos los Activos",
    pt: "Liquide todos os Ativos",
    de: "Liquidieren Sie alle VermÃ¶genswerte",
    it: "Liquidare tutte le AttivitÃ ",
    fr: "Liquiditez tous les Actifs",
  },
  rebirth: {
    en: "Rebirth",
    es: "Renacimiento",
    pt: "Renascimento",
    de: "Wiedergeburt",
    it: "Rinascita",
    fr: "Renaissance",
  },
  conquer10StarSystems: {
    en: "Conquer 10 Star Systems",
    es: "Conquista 10 Sistemas Estelares",
    pt: "Conquiste 10 Sistemas Estelares",
    de: "Erobere 10 Sternensysteme",
    it: "Conquista 10 Sistemi Stellari",
    fr: "ConquÃ©rez 10 SystÃ¨mes Stellaires",
  },
  conquer50StarSystems: {
    en: "Conquer 50 Star Systems",
    es: "Conquista 50 Sistemas Estelares",
    pt: "Conquiste 50 Sistemas Estelares",
    de: "Erobere 50 Sternensysteme",
    it: "Conquista 50 Sistemi Stellari",
    fr: "ConquÃ©rez 50 SystÃ¨mes Stellaires",
  },
  studyAllStarsInOneRun: {
    en: "Study All Stars in One Run",
    es: "Estudia todas las Estrellas en una Carrera",
    pt: "Estude todas as Estrelas em uma Partida",
    de: "Studiere alle Sterne in einem Durchlauf",
    it: "Studia tutte le Stelle in una Partita",
    fr: "Ã‰tudiez toutes les Ã‰toiles en une Partie",
  },
  adoptPhilosophy: {
    en: "Adopt a Philosophy",
    es: "Adopta una FilosofÃ­a",
    pt: "Adote uma Filosofia",
    de: "Adoptiere eine Philosophie",
    it: "Adotta una Filosofia",
    fr: "Adoptez une Philosophie",
  },
  discoverBlackHole: {
    en: "Discover a Black Hole",
    es: "Descubre un Agujero Negro",
    pt: "Descubra um Buraco Negro",
    de: "Entdecke ein Schwarzes Loch",
    it: "Scopri un Buco Nero",
    fr: "DÃ©couvrez un Trou Noir",
  },
  activateBlackHoleOver10x: {
    en: "Activate a Black Hole over 10x Time Warp",
    es: "Activa un Agujero Negro con Time Warp de mÃ¡s de 10x",
    pt: "Ative um Buraco Negro com Dobra Temporal superior a 10x",
    de: "Aktiviere ein Schwarzes Loch mit Ã¼ber 10x Zeitverzerrung",
    it: "Attiva un Buco Nero con Time Warp superiore a 10x",
    fr: "Activez un Trou Noir avec distorsion temporelle de plus de 10x",
  },
  findAncientManuscript: {
    en: "Find an Ancient Manuscript",
    es: "Encuentra un Manuscrito Antiguo",
    pt: "Encontre um Manuscrito Antigo",
    de: "Finde ein altes Manuskript",
    it: "Trova un Manoscritto Antico",
    fr: "Trouvez un Manuscrit Ancien",
  },
  conquerMegastructureSystem: {
    en: "Conquer a Megastructure System",
    es: "Conquista un Sistema de Megaestructuras",
    pt: "Conquiste um Sistema de Megasestruturas",
    de: "Erobere ein Megastruktur-System",
    it: "Conquista un Sistema di Megastrutture",
    fr: "ConquÃ©rez un SystÃ¨me de MÃ©gastructures",
  },
  bringDownMiaplacideanForceField: {
    en: "Bring down the Miaplacidean Force Field",
    es: "Derriba el Campo de Fuerza Miaplacideo",
    pt: "Derrube o Campo de ForÃ§a Miaplacideano",
    de: "Bring das Miaplacidean-Kraftfeld zum Einsturz",
    it: "Abbatti il Campo di Forza Miaplacideo",
    fr: "Abattez le Champ de Force MiaplacidÃ©en",
  },
  completeGame: {
    en: "Complete the Game",
    es: "Completa el Juego",
    pt: "Conclua o Jogo",
    de: "SchlieÃŸe das Spiel ab",
    it: "Completa il Gioco",
    fr: "Terminez le Jeu",
  },
  completeRunOnMiaplacidus: {
    en: "Complete a Run on Miaplacidus",
    es: "Completa una Carrera en Miaplacidus",
    pt: "Conclua uma Partida em Miaplacidus",
    de: "SchlieÃŸe einen Durchlauf auf Miaplacidus ab",
    it: "Completa una Partita su Miaplacidus",
    fr: "Terminez une Partie sur Miaplacidus",
  },
  haveFleetSizeOf50EachShipType: {
    en: "Have at least 50 of each Ship Type",
    es: "Ten al menos 50 de cada Tipo de Nave",
    pt: "Tenha pelo menos 50 de cada Tipo de Nave",
    de: "Habe mindestens 50 von jedem Schiffstyp",
    it: "Avere almeno 50 di ogni Tipo di Nave",
    fr: "Ayez au moins 50 de chaque Type de Vaisseau",
  },
  tryAllThemes: {
    en: "Try All Themes",
    es: "Prueba todos los Temas",
    pt: "Experimente todos os Temas",
    de: "Probiere alle Themen aus",
    it: "Prova tutti i Temi",
    fr: "Essayez tous les ThÃ¨mes",
  },
  buyCasinoPoints: {
    en: "Buy Some Casino Points",
    es: "Compra algunos Puntos de Casino",
    pt: "Compre Pontos de Cassino",
    de: "Kaufe einige Casino-Punkte",
    it: "Acquista alcuni Punti CasinÃ²",
    fr: "Achetez des Points de Casino",
  },
  winAllCasinoGames: {
    en: "Win A Prize In All Casino Games",
    es: "Gana un Premio en todos los Juegos del Casino",
    pt: "Ganhe um PrÃªmio em todos os Jogos do Cassino",
    de: "Gewinne einen Preis in allen Casino-Spielen",
    it: "Vinci un Premio in tutti i Giochi del CasinÃ²",
    fr: "Gagnez un Prix dans tous les Jeux de Casino",
  },
  winWheelSpecialPrize: {
    en: "Win A Wheel Of Fortune Special Prize",
    es: "Gana un Premio Especial de la Rueda de la Fortuna",
    pt: "Ganhe um PrÃªmio Especial da Roda da Fortuna",
    de: "Gewinne einen GlÃ¼cksrad-Sonderpreis",
    it: "Vinci un Premio Speciale della Ruota della Fortuna",
    fr: "Gagnez un Prix SpÃ©cial de la Roue de la Fortune",
  },
  restoreNearSpaceScannerArray: {
    en: "Restore The Near Space Scanner Array",
    es: "Restaura el Array de EscÃ¡ner del Espacio Cercano",
    pt: "Restaure o Array de Scanner do EspaÃ§o PrÃ³ximo",
    de: "Wiederherstellen des Nahraumscanner-Arrays",
    it: "Ripristina l\u0027Array Scanner dello Spazio Vicino",
    fr: "Restaurez le RÃ©seau de Scanners de l\u0027Espace Proche",
  },
  findCosmicRip: {
    en: "Find The Cosmic Rip",
    es: "Encuentra el Desgarro CÃ³smico",
    pt: "Encontre o Cosmic Rip",
    de: "Finde den kosmischen Riss",
    it: "Trova lo Strappo Cosmico",
    fr: "Trouvez le DÃ©chirure Cosmique",
  },
  gain1MTelemetryData: {
    en: "Gain 1M Telemetry Data",
    es: "Gana 1M de Datos de TelemetrÃ­a",
    pt: "Obtenha 1M de Dados de Telemetria",
    de: "Erhalte 1M Telemetriedaten",
    it: "Ottieni 1M di Dati di Telemetria",
    fr: "Gagnez 1M de DonnÃ©es de TÃ©lÃ©mÃ©trie",
  },
  closeCosmicRip: {
    en: "Close The Cosmic Rip",
    es: "Cierra el Desgarro CÃ³smico",
    pt: "Feche o Cosmic Rip",
    de: "SchlieÃŸe den kosmischen Riss",
    it: "Chiudi lo Strappo Cosmico",
    fr: "Fermez le DÃ©chirure Cosmique",
  },
  suffer5NegativeEvents: {
    en: "Suffer 5 Negative Instant Events",
    es: "Sufre 5 Eventos InstantÃ¡neos Negativos",
    pt: "Sofra 5 Eventos Negativos",
    de: "Erleide 5 negative Sofort-Ereignisse",
    it: "Subisci 5 Eventi Istantanei Negativi",
    fr: "Subissez 5 Ã‰vÃ©nements InstantanÃ©s NÃ©gatifs",
  },
  enjoyEndlessSummer: {
    en: "Enjoy An Endless Summer",
    es: "Disfruta un Verano sin Fin",
    pt: "Desfrute de um VerÃ£o Sem Fim",
    de: "GenieÃŸe einen endlosen Sommer",
    it: "Goditi un\u0027Estate Infinita",
    fr: "Profitez d\u0027un Ã‰tÃ© sans Fin",
  },
  completeOnboarding: {
    en: "Complete The Onboarding",
    es: "Completa la IntroducciÃ³n",
    pt: "Conclua a IntroduÃ§Ã£o",
    de: "SchlieÃŸe das Onboarding ab",
    it: "Completa l\u0027Onboarding",
    fr: "Terminez l\u0027IntÃ©gration",
  },
} as const;
