import type { LocaleId } from "./ids";

export const ECONOMY_BUILDING_NAMES = {
  scienceKit: {
    en: "Science Kit",
    es: "Kit de Ciencia",
    pt: "Kit de Ciência",
    de: "Wissenschaftsset",
    it: "Kit Scientifico",
    fr: "Kit Scientifique",
  },
  scienceClub: {
    en: "Open Science Club",
    es: "Abrir Club de Ciencia",
    pt: "Abrir Clube de Ciência",
    de: "Wissenschaftsclub Eröffnen",
    it: "Apri Club Scientifico",
    fr: "Ouvrir un Club Scientifique",
  },
  scienceLab: {
    en: "Open Science Lab",
    es: "Abrir Laboratorio de Ciencia",
    pt: "Abrir Laboratório de Ciência",
    de: "Wissenschaftslabor Eröffnen",
    it: "Apri Laboratorio Scientifico",
    fr: "Ouvrir un Laboratoire Scientifique",
  },
  powerPlant1: {
    en: "Power Plant",
    es: "Planta de Energía",
    pt: "Central Elétrica",
    de: "Kraftwerk",
    it: "Centrale Elettrica",
    fr: "Centrale Électrique",
  },
  powerPlant2: {
    en: "Solar Power Plant",
    es: "Planta de Energía Solar",
    pt: "Central de Energia Solar",
    de: "Solarkraftwerk",
    it: "Centrale Solare",
    fr: "Centrale Solaire",
  },
  powerPlant3: {
    en: "Advanced Power Plant",
    es: "Planta de Energía Avanzada",
    pt: "Central Elétrica Avançada",
    de: "Fortgeschrittenes Kraftwerk",
    it: "Centrale Elettrica Avanzata",
    fr: "Centrale Électrique Avancée",
  },
  battery1: {
    en: "Sodium Ion Battery",
    es: "Batería de Iones de Sodio",
    pt: "Bateria de Iões de Sódio",
    de: "Natrium-Ionen-Akku",
    it: "Batteria agli Ioni di Sodio",
    fr: "Batterie Sodium-Ion",
  },
  battery2: {
    en: "Lithium Ion Battery",
    es: "Batería de Iones de Litio",
    pt: "Bateria de Iões de Lítio",
    de: "Lithium-Ionen-Akku",
    it: "Batteria agli Ioni di Litio",
    fr: "Batterie Lithium-Ion",
  },
  battery3: {
    en: "Stellar Capacitor Array",
    es: "Matriz de Condensadores Estelares",
    pt: "Matriz de Condensadores Estelares",
    de: "Stellares Kondensatorfeld",
    it: "Matrice di Condensatori Stellari",
    fr: "Réseau de Condensateurs Stellaires",
  },
} as const satisfies Readonly<Record<string, Readonly<Record<LocaleId, string>>>>;
