import type { LocaleId, TechId } from "./ids";

/** Localized source descriptions, with markup removed for safe plain-text display. */
export const TECHNOLOGY_DESCRIPTIONS = {
  knowledgeSharing: {
    en: "Unlock Knowledge Sharing to improve research capacity and make new technologies accessible. / / Build Science Club",
    es: "Desbloquea el Compartir Conocimiento para mejorar la capacidad de investigación y hacer accesibles nuevas tecnologías. / / Construir Club de Ciencia",
    pt: "Desbloqueie o Compartilhamento de Conhecimento para melhorar a capacidade de pesquisa e tornar novas tecnologias acessíveis. / / Construir Clube de Ciência",
    de: "Schalte Wissensaustausch frei, um die Forschungskapazität zu verbessern und neue Technologien zugänglich zu machen. / / Wissenschaftsklub bauen",
    it: "Sblocca la Condivisione della Conoscenza per migliorare la capacità di ricerca e rendere accessibili nuove tecnologie. / / Costruisci Club Scientifico",
    fr: "Débloque le Partage de Connaissances pour améliorer la capacité de recherche et rendre accessibles de nouvelles technologies. / / Construire un Club Scientifique",
  },
  fusionTheory: {
    en: "Unlock Fusion Theory to unlock the potential of advanced fusion technologies for greater energy production. / / Prerequisite for Fusion technologies",
    es: "Desbloquea la Teoría de Fusión para desbloquear el potencial de tecnologías avanzadas de fusión para una mayor producción de energía. / / Prerrequisito para tecnologías de Fusión",
    pt: "Desbloqueie a Teoria da Fusão para explorar o potencial de tecnologias avançadas de fusão para maior produção de energia. / / Pré-requisito para tecnologias de Fusão",
    de: "Schalte Fusionstheorie frei, um das Potenzial fortgeschrittener Fusionstechnologien für höhere Energieproduktion zu nutzen. / / Voraussetzung für Fusionstechnologien",
    it: "Sblocca la Teoria della Fusione per sbloccare il potenziale di tecnologie avanzate di fusione per una maggiore produzione di energia. / / Prerequisito per tecnologie di Fusione",
    fr: "Débloque la Théorie de la Fusion pour libérer le potentiel des technologies avancées de fusion pour une plus grande production d'énergie. / / Prérequis pour les technologies de Fusion",
  },
  hydrogenFusion: {
    en: "Unlock Hydrogen Fusion to explore the potential of fusing Hydrogen atoms for sustainable energy. / / Unlock Helium resource",
    es: "Desbloquea la Fusión de Hidrógeno para explorar el potencial de la fusión de átomos de Hidrógeno para energía sostenible. / / Desbloquear recurso de Helio",
    pt: "Desbloqueie a Fusão de Hidrogênio para explorar o potencial da fusão de átomos de Hidrogênio para energia sustentável. / / Desbloquear recurso de Hélio",
    de: "Schalte Wasserstofffusion frei, um das Potenzial der Verschmelzung von Wasserstoffatomen für nachhaltige Energie zu erkunden. / / Helium-Ressource freischalten",
    it: "Sblocca la Fusione dell'Idrogeno per esplorare il potenziale della fusione di atomi di Idrogeno per energia sostenibile. / / Sblocca risorsa Elio",
    fr: "Débloque la Fusion de l'Hydrogène pour explorer le potentiel de la fusion d'atomes d'Hydrogène pour une énergie durable. / / Débloquer la ressource Hélium",
  },
  heliumFusion: {
    en: "Unlock Helium Fusion to fuse Helium atoms, unlocking greater energy production and new resource chains. / / Prerequisite for Carbon Fusion",
    es: "Desbloquea la Fusión de Helio para fusionar átomos de Helio, desbloqueando una mayor producción de energía y nuevas cadenas de recursos. / / Prerrequisito para Fusión de Carbono",
    pt: "Desbloqueia a Fusão de Hélio para fundir átomos de Hélio, desbloqueando maior produção de energia e novas cadeias de recursos. / / Pré-requisito para Fusão de Carbono",
    de: "Schalte Heliumfusion frei, um Heliumatome zu verschmelzen und höhere Energieproduktion und neue Ressourcenketten freizuschalten. / / Voraussetzung für Kohlenstoff-Fusion",
    it: "Sblocca la Fusione dell'Elio per fondere atomi di Elio, sbloccando una maggiore produzione di energia e nuove catene di risorse. / / Prerequisito per Fusione del Carbonio",
    fr: "Débloque la Fusion de l'Hélium pour fusionner des atomes d'hélium, débloquant une production d'énergie plus élevée et de nouvelles chaînes de ressources. / / Prérequis pour la Fusion du Carbone",
  },
  carbonFusion: {
    en: "Unlock Carbon Fusion to fuse Carbon atoms, unlocking the path to heavier element fusion. / / Prerequisite for Oxygen and Neon Fusion",
    es: "Desbloquea la Fusión de Carbono para fusionar átomos de Carbono, abriendo el camino a la fusión de elementos más pesados. / / Prerrequisito para Fusión de Oxígeno y Neón",
    pt: "Desbloqueia a Fusão de Carbono para fundir átomos de Carbono, abrindo caminho para a fusão de elementos mais pesados. / / Pré-requisito para Fusão de Oxigênio e Néon",
    de: "Schalte Kohlenstoff-Fusion frei, um Kohlenstoffatome zu verschmelzen und den Weg zur Fusion schwererer Elemente zu ebnen. / / Voraussetzung für Sauerstoff- und Neon-Fusion",
    it: "Sblocca la Fusione del Carbonio per fondere atomi di Carbonio, aprendo la strada alla fusione di elementi più pesanti. / / Prerequisito per Fusione di Ossigeno e Neon",
    fr: "Débloque la Fusion du Carbone pour fusionner des atomes de carbone, ouvrant la voie à la fusion d'éléments plus lourds. / / Prérequis pour la Fusion de l'Oxygène et du Néon",
  },
  basicPowerGeneration: {
    en: "Unlock Basic Power Generation to lay the foundation for generating energy and powering essential systems. / / Build Power Plant",
    es: "Desbloquea Generación de Energía Básica para sentar las bases para generar energía y alimentar sistemas esenciales. / / Construir Central de Energía",
    pt: "Desbloqueie Geração Básica de Energia para estabelecer as bases para gerar energia e alimentar sistemas essenciais. / / Construir Central de Energia",
    de: "Schalte Grundlegende Energieerzeugung frei, um das Fundament für Energieerzeugung und Versorgung wichtiger Systeme zu legen. / / Kraftwerk bauen",
    it: "Sblocca Generazione di Energia di Base per gettare le basi per la produzione di energia e l'alimentazione dei sistemi essenziali. / / Costruisci Centrale Elettrica",
    fr: "Débloque la Génération d'Énergie de Base pour poser les fondations de la production d'énergie et alimenter les systèmes essentiels. / / Construire une Centrale Électrique",
  },
  sodiumIonPowerStorage: {
    en: "Unlock Sodium-Ion Power Storage to build a Sodium Ion Battery for storing energy generated by your systems. / / Build Sodium Ion Battery",
    es: "Desbloquea Almacenamiento de Energía de Ion de Sodio para construir una Batería de Ion de Sodio para almacenar la energía generada por tus sistemas. / / Construir Batería de Ion de Sodio",
    pt: "Desbloqueie Armazenamento de Energia de Íon de Sódio para construir uma Bateria de Íon de Sódio e armazenar a energia gerada pelos seus sistemas. / / Construir Bateria de Íon de Sódio",
    de: "Schalte Natrium-Ionen-Energiespeicherung frei, um eine Natrium-Ionen-Batterie zum Speichern von Energie zu bauen, die von deinen Systemen erzeugt wird. / / Natrium-Ionen-Batterie bauen",
    it: "Sblocca Immagazzinamento Energia Ioni di Sodio per costruire una Batteria agli Ioni di Sodio per immagazzinare l'energia generata dai tuoi sistemi. / / Costruisci Batteria agli Ioni di Sodio",
    fr: "Débloque le Stockage d'Énergie Sodium-Ion pour construire une Batterie Sodium-Ion pour stocker l'énergie générée par vos systèmes. / / Construire une Batterie Sodium-Ion",
  },
  solarPowerGeneration: {
    en: "Unlock Solar Power Generation to harness renewable solar energy, reducing reliance on non-renewable resources. / / Build Solar Power Plant",
    es: "Desbloquea Generación de Energía Solar para aprovechar la energía solar renovable, reduciendo la dependencia de recursos no renovables. / / Construir Central Solar",
    pt: "Desbloqueie Geração de Energia Solar para aproveitar a energia solar renovável, reduzindo a dependência de recursos não renováveis. / / Construir Central Solar",
    de: "Schalte Solarenergieerzeugung frei, um erneuerbare Solarenergie zu nutzen und die Abhängigkeit von nicht erneuerbaren Ressourcen zu verringern. / / Solarkraftwerk bauen",
    it: "Sblocca Generazione di Energia Solare per sfruttare l'energia solare rinnovabile, riducendo la dipendenza dalle risorse non rinnovabili. / / Costruisci Centrale Solare",
    fr: "Débloque la Génération d'Énergie Solaire pour exploiter l'énergie solaire renouvelable, réduisant la dépendance aux ressources non renouvelables. / / Construire une Centrale Solaire",
  },
  giganticTurbines: {
    en: "Unlock Gigantic Turbines to build massive, high-efficiency turbines for advanced power generation. / / Prerequisite for Advanced Power Plant",
    es: "Desbloquea Turbinas Gigantes para construir turbinas masivas y de alta eficiencia para generación de energía avanzada. / / Prerrequisito para Central de Energía Avanzada",
    pt: "Desbloqueie Turbinas Gigantes para construir turbinas massivas e de alta eficiência para geração avançada de energia. / / Pré-requisito para Central de Energia Avançada",
    de: "Schalte Gigantische Turbinen frei, um massive, hocheffiziente Turbinen für fortgeschrittene Energieerzeugung zu bauen. / / Voraussetzung für Fortgeschrittenes Kraftwerk",
    it: "Sblocca Turbine Giganti per costruire turbine massive e ad alta efficienza per la generazione di energia avanzata. / / Prerequisito per Centrale Elettrica Avanzata",
    fr: "Débloque les Turbines Géantes pour construire des turbines massives et haute efficacité pour la production d'énergie avancée. / / Prérequis pour Centrale Électrique Avancée",
  },
  advancedPowerGeneration: {
    en: "Unlock Advanced Power Generation to increase energy output, powering more complex systems and facilities, and reveal Lithium Ion Battery. / / Build Advanced Power Plant / Reveal Lithium Ion Battery",
    es: "Desbloquea Generación de Energía Avanzada para aumentar la producción de energía, alimentar sistemas e instalaciones más complejas, y revelar la Batería de Ion de Litio. / / Construir Central de Energía Avanzada / Revelar Batería de Ion de Litio",
    pt: "Desbloqueie Geração Avançada de Energia para aumentar a produção de energia, alimentar sistemas e instalações mais complexos e revelar a Bateria de Íon de Lítio. / / Construir Central de Energia Avançada / Revelar Bateria de Íon de Lítio",
    de: "Schalte Fortgeschrittene Energieerzeugung frei, um die Energieausgabe zu erhöhen, komplexere Systeme und Anlagen zu versorgen und den Lithium-Ionen-Akku freizuschalten. / / Fortgeschrittenes Kraftwerk bauen / Lithium-Ionen-Akku freischalten",
    it: "Sblocca Generazione di Energia Avanzata per aumentare la produzione di energia, alimentare sistemi e strutture più complessi, e svelare la Batteria agli Ioni di Litio. / / Costruisci Centrale Elettrica Avanzata / Svela Batteria agli Ioni di Litio",
    fr: "Débloque la Génération d'Énergie Avancée pour augmenter la production d'énergie, alimenter des systèmes et installations plus complexes, et révéler la Batterie Lithium-Ion. / / Construire une Centrale Électrique Avancée / Révéler la Batterie Lithium-Ion",
  },
  rocketComposites: {
    en: "Unlock Rocket Composites to build rocket components to mine in space, and level 3 and 4 AutoBuyers. / / Unlock Launch Pad Tab",
    es: "Desbloquea Compuestos de Cohetes para construir componentes de cohetes para minar en el espacio, y Compradores Automáticos de nivel 3 y 4. / / Desbloquear Pestaña de Plataforma de Lanzamiento",
    pt: "Desbloqueie Compostos de Foguetes para construir componentes de foguetes para minerar no espaço, além dos Compradores Automáticos de nível 3 e 4. / / Desbloquear Aba da Plataforma de Lançamento",
    de: "Schalte Raketenverbundwerkstoffe frei, um Raketenkomponenten für den Weltraumbergbau zu bauen und Stufe 3 und 4 Auto-Käufer. / / Startplattform-Tab freischalten",
    it: "Sblocca Compositi per Razzi per costruire componenti di razzi per estrarre nello spazio, e Acquirenti Automatici di livello 3 e 4. / / Sblocca Scheda Piattaforma di Lancio",
    fr: "Débloque les Composites de Fusées pour construire des composants de fusées pour miner dans l'espace, et les acheteurs automatiques de niveau 3 et 4. / / Débloquer l'onglet Rampe de Lancement",
  },
  advancedFuels: {
    en: "Unlock Advanced Fuels to fuel your Space Mining vessels / / Create Rocket Fuel",
    es: "Desbloquea Combustibles Avanzados para abastecer tus naves de Minería Espacial / / Crear Combustible de Cohete",
    pt: "Desbloqueie Combustíveis Avançados para abastecer suas naves de Mineração Espacial / / Criar Combustível de Foguete",
    de: "Schalte Fortgeschrittene Treibstoffe frei, um deine Weltraum-Bergbau-Schiffe zu betanken / / Raketentreibstoff herstellen",
    it: "Sblocca Carburanti Avanzati per rifornire le tue navi da Miniera Spaziale / / Crea Carburante per Razzi",
    fr: "Débloque les Carburants Avancés pour alimenter vos vaisseaux d'extraction spatiale / / Créer du Carburant de Fusée",
  },
  planetaryNavigation: {
    en: "Unlock the ability to travel to Asteroids. / / Travel To Asteroids",
    es: "Desbloquea la capacidad de viajar a Asteroides. / / Viajar a Asteroides",
    pt: "Desbloqueie a capacidade de viajar para Asteroides. / / Viajar para Asteroides",
    de: "Schalte die Fähigkeit frei, zu Asteroiden zu reisen. / / Zu Asteroiden reisen",
    it: "Sblocca la capacità di viaggiare verso gli Asteroidi. / / Viaggia verso gli Asteroidi",
    fr: "Débloque la capacité de voyager vers les Astéroïdes. / / Voyager vers les Astéroïdes",
  },
  neonFusion: {
    en: "Unlock Neon Fusion to fuse Neon atoms, requiring both Carbon Fusion and Noble Gas Collection. / / Requires Carbon Fusion and Noble Gas Collection",
    es: "Desbloquea la Fusión de Neón para fusionar átomos de Neón, requiriendo tanto Fusión de Carbono como Recolección de Gases Nobles. / / Requiere Fusión de Carbono y Recolección de Gases Nobles",
    pt: "Desbloqueia a Fusão de Néon para fundir átomos de Néon, exigindo tanto Fusão de Carbono quanto Coleta de Gases Nobres. / / Requer Fusão de Carbono e Coleta de Gases Nobres",
    de: "Schalte Neon-Fusion frei, um Neonatome zu verschmelzen, erfordert sowohl Kohlenstoff-Fusion als auch Edelgassammlung. / / Erfordert Kohlenstoff-Fusion und Edelgassammlung",
    it: "Sblocca la Fusione del Neon per fondere atomi di Neon, richiede sia Fusione del Carbonio che Raccolta di Gas Nobili. / / Richiede Fusione del Carbonio e Raccolta di Gas Nobili",
    fr: "Débloque la Fusion du Néon pour fusionner des atomes de néon, nécessitant à la fois la Fusion du Carbone et la Collection de Gaz Nobles. / / Nécessite Fusion du Carbone et Collection de Gaz Nobles",
  },
  oxygenFusion: {
    en: "Unlock Oxygen Fusion to fuse Oxygen atoms, continuing the path to heavier element fusion chains. / / Prerequisite for Silicon Fusion",
    es: "Desbloquea la Fusión de Oxígeno para fusionar átomos de Oxígeno, continuando el camino hacia cadenas de fusión de elementos más pesados. / / Prerrequisito para Fusión de Silicio",
    pt: "Desbloqueia a Fusão de Oxigênio para fundir átomos de Oxigênio, continuando o caminho para cadeias de fusão de elementos mais pesados. / / Pré-requisito para Fusão de Silício",
    de: "Schalte Sauerstoff-Fusion frei, um Sauerstoffatome zu verschmelzen und den Weg zu Fusionketten schwererer Elemente fortzusetzen. / / Voraussetzung für Silizium-Fusion",
    it: "Sblocca la Fusione dell'Ossigeno per fondere atomi di Ossigeno, continuando il percorso verso le catene di fusione di elementi più pesanti. / / Prerequisito per Fusione del Silicio",
    fr: "Débloque la Fusion de l'Oxygène pour fusionner des atomes d'oxygène, poursuivant la voie vers les chaînes de fusion d'éléments plus lourds. / / Prérequis pour la Fusion du Silicium",
  },
  compounds: {
    en: "Unlock Compounds to gain access to new materials and enhance your manufacturing capabilities. / / Unlock Compounds Tab",
    es: "Desbloquea Compuestos para acceder a nuevos materiales y mejorar tus capacidades de fabricación. / / Desbloquear Pestaña de Compuestos",
    pt: "Desbloqueie Compostos para acessar novos materiais e melhorar suas capacidades de fabricação. / / Desbloquear Aba de Compostos",
    de: "Schalte Verbindungen frei, um Zugang zu neuen Materialien zu erhalten und deine Fertigungsfähigkeiten zu verbessern. / / Verbindungen-Tab freischalten",
    it: "Sblocca Composti per accedere a nuovi materiali e migliorare le tue capacità di produzione. / / Sblocca Scheda Composti",
    fr: "Débloque les Composés pour accéder à de nouveaux matériaux et améliorer vos capacités de fabrication. / / Débloquer l'onglet Composés",
  },
  siliconFusion: {
    en: "Unlock Silicon Fusion to fuse Silicon atoms, the pinnacle of fusion energy technology. / / Prerequisite for Neutron Capture",
    es: "Desbloquea la Fusión de Silicio para fusionar átomos de Silicio, el pináculo de la tecnología de energía de fusión. / / Prerrequisito para Captura de Neutrones",
    pt: "Desbloqueia a Fusão de Silício para fundir átomos de Silício, o ápice da tecnologia de energia de fusão. / / Pré-requisito para Captura de Nêutrons",
    de: "Schalte Silizium-Fusion frei, um Siliziumatome zu verschmelzen, der Höhepunkt der Fusionstechnologie. / / Voraussetzung für Neutronen-Einfang",
    it: "Sblocca la Fusione del Silicio per fondere atomi di Silicio, il culmine della tecnologia dell'energia da fusione. / / Prerequisito per Cattura di Neutroni",
    fr: "Débloque la Fusion du Silicium pour fusionner des atomes de silicium, le pinacle de la technologie d'énergie de fusion. / / Prérequis pour la Capture de Neutrons",
  },
  aggregateMixing: {
    en: "Unlock Aggregate Mixing to combine materials, enabling production of concrete and other essential construction compounds. / / Unlock Concrete Production",
    es: "Desbloquea la Mezcla de Agregados para combinar materiales, permitiendo la producción de hormigón y otros compuestos de construcción esenciales. / / Desbloquear Producción de Hormigón",
    pt: "Desbloqueia a Mistura de Agregados para combinar materiais, permitindo a produção de concreto e outros compostos de construção essenciais. / / Desbloquear Produção de Concreto",
    de: "Schalte Zuschlagstoffmischung frei, um Materialien zu kombinieren und Produktion von Beton und anderen wesentlichen Bauverbindungen zu ermöglichen. / / Betonproduktion freischalten",
    it: "Sblocca la Miscela di Aggregati per combinare materiali, consentendo la produzione di calcestruzzo e altri composti da costruzione essenziali. / / Sblocca Produzione di Calcestruzzo",
    fr: "Débloque le Mélange d'Agrégats pour combiner des matériaux, permettant la production de béton et d'autres composés de construction essentiels. / / Débloquer la Production de Béton",
  },
  steelFoundries: {
    en: "Unlock Steel Foundries to produce high-strength steel alloys from iron, enabling advanced manufacturing and construction. / / Unlock Steel compound",
    es: "Desbloquea Fundiciones de Acero para producir aleaciones de acero de alta resistencia a partir de hierro, permitiendo fabricación y construcción avanzadas. / / Desbloquear compuesto de Acero",
    pt: "Desbloqueie Fundições de Aço para produzir ligas de aço de alta resistência a partir de ferro, permitindo fabricação e construção avançadas. / / Desbloquear composto de Aço",
    de: "Schalte Stahlgiessereien frei, um hochfeste Stahllegierungen aus Eisen herzustellen, was fortgeschrittene Fertigung und Bauen ermöglicht. / / Stahl-Verbindung freischalten",
    it: "Sblocca Fonderie d'Acciaio per produrre leghe d'acciaio ad alta resistenza dal ferro, abilitando produzione e costruzione avanzate. / / Sblocca composto Acciaio",
    fr: "Débloque les Fonderies d'Acier pour produire des alliages d'acier à haute résistance à partir de fer, permettant la fabrication et la construction avancées. / / Débloquer le composé Acier",
  },
  nanoTubeTechnology: {
    en: "Unlock NanoTube Technology to create ultra-strong carbon nanotubes, enabling advanced construction and mega-structures. / / Unlock Rocket Composites and Advanced Construction",
    es: "Desbloquea la Tecnología de Nanotubos para crear nanotubos de carbono ultra resistentes, permitiendo la construcción avanzada y mega-estructuras. / / Desbloquear Compuestos de Cohetes y Construcción Avanzada",
    pt: "Desbloqueia a Tecnologia de Nanotubos para criar nanotubos de carbono ultrarresistentes, permitindo construção avançada e megaestruturas. / / Desbloquear Compostos de Foguete e Construção Avançada",
    de: "Schalte Nanoröhrchen-Technologie frei, um ultra-starke Kohlenstoff-Nanoröhrchen zu erstellen und fortschrittlichen Bau und Mega-Strukturen zu ermöglichen. / / Raketen-Verbundwerkstoffe und Fortgeschrittenen Bau freischalten",
    it: "Sblocca la Tecnologia dei Nanotubi per creare nanotubi di carbonio ultra resistenti, consentendo la costruzione avanzata e le mega-strutture. / / Sblocca Compositi per Razzi e Costruzione Avanzata",
    fr: "Débloque la Technologie des Nanotubes pour créer des nanotubes de carbone ultra-résistants, permettant la construction avancée et les mégastructures. / / Débloquer les Composites de Fusées et la Construction Avancée",
  },
  hydroCarbons: {
    en: "Unlock HydroCarbons to process carbon compounds with hydrogen, enabling production of plastic and fuel. / / Unlock Plastic and Fuel production",
    es: "Desbloquea los Hidrocarburos para procesar compuestos de carbono con hidrógeno, permitiendo la producción de plástico y combustible. / / Desbloquear producción de Plástico y Combustible",
    pt: "Desbloqueia os Hidrocarbonetos para processar compostos de carbono com hidrogênio, permitindo a produção de plástico e combustível. / / Desbloquear produção de Plástico e Combustível",
    de: "Schalte Kohlenwasserstoffe frei, um Kohlenstoffverbindungen mit Wasserstoff zu verarbeiten und Produktion von Kunststoff und Treibstoff zu ermöglichen. / / Produktion von Kunststoff und Treibstoff freischalten",
    it: "Sblocca gli Idrocarburi per elaborare composti di carbonio con idrogeno, consentendo la produzione di plastica e carburante. / / Sblocca produzione di Plastica e Carburante",
    fr: "Débloque les Hydrocarbures pour traiter les composés de carbone avec de l'hydrogène, permettant la production de plastique et de carburant. / / Débloquer la production de Plastique et Carburant",
  },
  stellarCartography: {
    en: "Unlock Stellar Cartography to map distant stars and unlock new astronomical research capabilities. / / Unlock Star Map",
    es: "Desbloquea la Cartografía Estelar para mapear estrellas distantes y desbloquear nuevas capacidades de investigación astronómica. / / Desbloquear Mapa Estelar",
    pt: "Desbloqueie a Cartografia Estelar para mapear estrelas distantes e desbloquear novas capacidades de pesquisa astronômica. / / Desbloquear Mapa Estelar",
    de: "Schalte Sternenkartografie frei, um entfernte Sterne zu kartieren und neue astronomische Forschungsfähigkeiten freizuschalten. / / Sternenkarte freischalten",
    it: "Sblocca la Cartografia Stellare per mappare stelle lontane e sbloccare nuove capacità di ricerca astronomica. / / Sblocca Mappa Stellare",
    fr: "Débloque la Cartographie Stellaire pour cartographier des étoiles lointaines et débloquer de nouvelles capacités de recherche astronomique. / / Débloquer la Carte des Étoiles",
  },
  quantumComputing: {
    en: "Unlock Quantum Computing to harness quantum mechanics for advanced computational power. / / Build Quantum Computing Lab",
    es: "Desbloquea la Computación Cuántica para aprovechar la mecánica cuántica para una potencia computacional avanzada. / / Construir Laboratorio de Computación Cuántica",
    pt: "Desbloqueia a Computação Quântica para aproveitar a mecânica quântica para obter poder computacional avançado. / / Construir Laboratório de Computação Quântica",
    de: "Schalte Quantencomputing frei, um Quantenmechanik für fortschrittliche Rechenleistung zu nutzen. / / Quantencomputing-Labor bauen",
    it: "Sblocca il Calcolo Quantistico per sfruttare la meccanica quantistica per potenza computazionale avanzata. / / Costruisci Laboratorio di Calcolo Quantistico",
    fr: "Débloque l'Informatique Quantique pour exploiter la mécanique quantique pour une puissance de calcul avancée. / / Construire un Laboratoire d'Informatique Quantique",
  },
  scienceLaboratories: {
    en: "Unlock Science Laboratories to establish large-scale labs dedicated to conducting cutting-edge research. / / Build Science Laboratory",
    es: "Desbloquea Laboratorios Científicos para establecer laboratorios a gran escala dedicados a realizar investigación de vanguardia. / / Construir Laboratorio Científico",
    pt: "Desbloqueie Laboratórios Científicos para estabelecer laboratórios de grande escala dedicados à realização de pesquisas de ponta. / / Construir Laboratório Científico",
    de: "Schalte Wissenschaftslabore frei, um grosse Labore einzurichten, die der Durchführung bahnbrechender Forschung gewidmet sind. / / Wissenschaftslabor bauen",
    it: "Sblocca Laboratori Scientifici per stabilire laboratori su larga scala dedicati a condurre ricerche all'avanguardia. / / Costruisci Laboratorio Scientifico",
    fr: "Débloque les Laboratoires Scientifiques pour établir des laboratoires à grande échelle dédiés à la recherche de pointe. / / Construire un Laboratoire Scientifique",
  },
  nobleGasCollection: {
    en: "Unlock Noble Gas Collection to store and manage rare noble gases, essential for high-end applications. / / Prerequisite for Neon Fusion (with Carbon Fusion)",
    es: "Desbloquea la Recolección de Gases Nobles para almacenar y gestionar gases nobles raros, esenciales para aplicaciones de alta gama. / / Prerrequisito para Fusión de Neón (con Fusión de Carbono)",
    pt: "Desbloqueie a Coleta de Gases Nobres para armazenar e gerenciar gases nobres raros, essenciais para aplicações de alta tecnologia. / / Pré-requisito para Fusão de Neônio (com Fusão de Carbono)",
    de: "Schalte Edelgassammlung frei, um seltene Edelgase zu speichern und zu verwalten, die für High-End-Anwendungen unerlässlich sind. / / Voraussetzung für Neon-Fusion (mit Kohlenstoff-Fusion)",
    it: "Sblocca la Raccolta di Gas Nobili per immagazzinare e gestire gas nobili rari, essenziali per applicazioni di alto livello. / / Prerequisito per Fusione di Neon (con Fusione di Carbonio)",
    fr: "Débloque la Collection de Gaz Nobles pour stocker et gérer des gaz nobles rares, essentiels pour les applications haut de gamme. / / Prérequis pour la Fusion de Néon (avec Fusion de Carbone)",
  },
  neutronCapture: {
    en: "Unlock Neutron Capture to harness neutron absorption, enabling production of rare isotopes and extreme energy yields. / / Unlock Isotope Production",
    es: "Desbloquea la Captura de Neutrones para aprovechar la absorción de neutrones, permitiendo la producción de isótopos raros y rendimientos de energía extremos. / / Desbloquear Producción de Isótopos",
    pt: "Desbloqueia a Captura de Nêutrons para aproveitar a absorção de nêutrons, permitindo a produção de isótopos raros e rendimentos extremos de energia. / / Desbloquear Produção de Isótopos",
    de: "Schalte Neutronen-Einfang frei, um Neutronenabsorption zu nutzen und Produktion seltener Isotope und extreme Energieerträge zu ermöglichen. / / Isotopenproduktion freischalten",
    it: "Sblocca la Cattura di Neutroni per sfruttare l'assorbimento di neutroni, consentendo la produzione di isotopi rari e rese energetiche estreme. / / Sblocca Produzione di Isotopi",
    fr: "Débloque la Capture de Neutrons pour exploiter l'absorption de neutrons, permettant la production d'isotopes rares et des rendements énergétiques extrêmes. / / Débloquer la Production d'Isotopes",
  },
  glassManufacture: {
    en: "Unlock Glass Manufacture to produce glass, essential for advanced construction, telescopes, and stellar cartography. / / Unlock Telescope Construction",
    es: "Desbloquea la Fabricación de Vidrio para producir vidrio, esencial para construcción avanzada, telescopios y cartografía estelar. / / Desbloquear Construcción de Telescopios",
    pt: "Desbloqueia a Fabricação de Vidro para produzir vidro, essencial para construção avançada, telescópios e cartografia estelar. / / Desbloquear Construção de Telescópios",
    de: "Schalte Glasherstellung frei, um Glas zu produzieren, unverzichtbar für fortgeschrittenen Bau, Teleskope und Sternenkartografie. / / Teleskopbau freischalten",
    it: "Sblocca la Produzione di Vetro per produrre vetro, essenziale per costruzione avanzata, telescopi e cartografia stellare. / / Sblocca Costruzione di Telescopi",
    fr: "Débloque la Fabrication de Verre pour produire du verre, essentiel pour la construction avancée, les télescopes et la cartographie stellaire. / / Débloquer la Construction de Télescopes",
  },
  atmosphericTelescopes: {
    en: "Unlock Atmospheric Telescopes to gather data and insights about nearby stars and cosmic bodies. / / Reveal Star Data",
    es: "Desbloquea Telescopios Atmosféricos para recopilar datos e información sobre estrellas cercanas y cuerpos cósmicos. / / Revelar Datos Estelares",
    pt: "Desbloqueie Telescópios Atmosféricos para coletar dados e informações sobre estrelas próximas e corpos cósmicos. / / Revelar Dados Estelares",
    de: "Schalte Atmosphärenteleskope frei, um Daten und Erkenntnisse über nahegelegene Sterne und kosmische Körper zu sammeln. / / Sternendaten aufdecken",
    it: "Sblocca Telescopi Atmosferici per raccogliere dati e informazioni sulle stelle vicine e i corpi cosmici. / / Rivela Dati Stellari",
    fr: "Débloque les Télescopes Atmosphériques pour collecter des données et des informations sur les étoiles proches et les corps cosmiques. / / Révéler les Données Stellaires",
  },
  fusionEfficiencyI: {
    en: "Unlock Fusion Efficiency I to improve the performance and energy output of fusion reactions. / / Fusion Efficiency +20%",
    es: "Desbloquea Eficiencia de Fusión I para mejorar el rendimiento y la producción de energía de las reacciones de fusión. / / Eficiencia de Fusión +20%",
    pt: "Desbloqueie Eficiência de Fusão I para melhorar o desempenho e a produção de energia das reações de fusão. / / Eficiência de Fusão +20%",
    de: "Schalte Fusionseffizienz I frei, um die Leistung und Energieausbeute von Fusionsreaktionen zu verbessern. / / Fusionseffizienz +20%",
    it: "Sblocca Efficienza di Fusione I per migliorare le prestazioni e la produzione di energia delle reazioni di fusione. / / Efficienza di Fusione +20%",
    fr: "Débloque l'Efficacité de Fusion I pour améliorer les performances et la production d'énergie des réactions de fusion. / / Efficacité de Fusion +20%",
  },
  fusionEfficiencyII: {
    en: "Unlock Fusion Efficiency II to maximize fusion efficiency, leading to higher energy yields and lower waste. / / Fusion Efficiency +20%",
    es: "Desbloquea Eficiencia de Fusión II para maximizar la eficiencia de fusión, logrando mayores rendimientos de energía y menos residuos. / / Eficiencia de Fusión +20%",
    pt: "Desbloqueie Eficiência de Fusão II para maximizar a eficiência da fusão, obtendo maiores rendimentos de energia e menos resíduos. / / Eficiência de Fusão +20%",
    de: "Schalte Fusionseffizienz II frei, um die Fusionseffizienz zu maximieren, was zu höheren Energieerträgen und geringerem Abfall führt. / / Fusionseffizienz +20%",
    it: "Sblocca Efficienza di Fusione II per massimizzare l'efficienza della fusione, portando a maggiori rese energetiche e minori sprechi. / / Efficienza di Fusione +20%",
    fr: "Débloque l'Efficacité de Fusion II pour maximiser l'efficacité de la fusion, conduisant à des rendements énergétiques plus élevés et moins de déchets. / / Efficacité de Fusion +20%",
  },
  fusionEfficiencyIII: {
    en: "Unlock Fusion Efficiency III to achieve fully optimized, 100% efficient fusion energy generation. / / 100% Fusion Efficiency",
    es: "Desbloquea Eficiencia de Fusión III para lograr una generación de energía de fusión completamente optimizada y 100% eficiente. / / 100% Eficiencia de Fusión",
    pt: "Desbloqueie Eficiência de Fusão III para alcançar uma geração de energia de fusão totalmente otimizada e 100% eficiente. / / 100% de Eficiência de Fusão",
    de: "Schalte Fusionseffizienz III frei, um vollständig optimierte, 100% effiziente Fusionsenergieerzeugung zu erreichen. / / 100% Fusionseffizienz",
    it: "Sblocca Efficienza di Fusione III per ottenere una generazione di energia da fusione completamente ottimizzata e 100% efficiente. / / 100% Efficienza di Fusione",
    fr: "Débloque l'Efficacité de Fusion III pour atteindre une génération d'énergie de fusion complètement optimisée et 100% efficace. / / 100% Efficacité de Fusion",
  },
  orbitalConstruction: {
    en: "Unlock Orbital Construction to build starship modules and reveal Stellar Capacitor Array.. / / Unlock Starship Section in InterStellar Tab / Reveal Stellar Capacitor Array",
    es: "Desbloquea Construcción Orbital para construir módulos de nave estelar y revelar el Arreglo de Capacitores Estelares. / / Desbloquear Sección de Nave Estelar en Pestaña Interestelar / Revelar Arreglo de Capacitores Estelares",
    pt: "Desbloqueie Construção Orbital para construir módulos de nave estelar e revelar o Conjunto de Capacitores Estelares. / / Desbloquear Seção de Nave Estelar na Aba Interestelar / Revelar Conjunto de Capacitores Estelares",
    de: "Schalte Orbitale Konstruktion frei, um Raumschiffmodule zu bauen und das Sternenkondensator-Array freizuschalten. / / Raumschiff-Bereich im Interstellar-Tab freischalten / Sternenkondensator-Array freischalten",
    it: "Sblocca Costruzione Orbitale per costruire moduli di astronave e svelare l'Array di Condensatori Stellari. / / Sblocca Sezione Astronave nella Scheda Interstellare / Svela Array di Condensatori Stellari",
    fr: "Débloque la Construction Orbitale pour construire des modules de vaisseau stellaire et révéler le Réseau de Condensateurs Stellaires. / / Débloquer la Section Vaisseau Stellaire dans l'onglet Interstellaire / Révéler le Réseau de Condensateurs Stellaires",
  },
  antimatterEngines: {
    en: "Unlock Antimatter Engines to build interstellar propulsion systems. / / Build Starship Antimatter Engines",
    es: "Desbloquea Motores de Antimateria para construir sistemas de propulsión interestelar. / / Construir Motores de Antimateria para Nave Estelar",
    pt: "Desbloqueie Motores de Antimatéria para construir sistemas de propulsão interestelar. / / Construir Motores de Antimatéria para Nave Estelar",
    de: "Schalte Antimaterie-Antriebe frei, um interstellare Antriebssysteme zu bauen. / / Raumschiff-Antimaterie-Antriebe bauen",
    it: "Sblocca Motori ad Antimateria per costruire sistemi di propulsione interstellare. / / Costruisci Motori ad Antimateria per Astronave",
    fr: "Débloque les Moteurs à Antimatière pour construire des systèmes de propulsion interstellaire. / / Construire des Moteurs à Antimatière pour Vaisseau Stellaire",
  },
  FTLTravelTheory: {
    en: "Unlock FTL Travel Theory to research faster-than-light travel. / / Can Launch Starship",
    es: "Desbloquea Teoría de Viaje FTL para investigar viajes más rápidos que la luz. / / Puede Lanzar Nave Estelar",
    pt: "Desbloqueie Teoria de Viagem FTL para pesquisar viagens mais rápidas que a luz. / / Pode Lançar Nave Estelar",
    de: "Schalte FTL-Reisetheorie frei, um Reisen schneller als Licht zu erforschen. / / Kann Raumschiff starten",
    it: "Sblocca Teoria del Viaggio FTL per ricercare viaggi superluminali. / / Può Lanciare Astronave",
    fr: "Débloque la Théorie de Voyage FTL pour rechercher des voyages plus rapides que la lumière. / / Peut Lancer un Vaisseau Stellaire",
  },
  lifeSupportSystems: {
    en: "Unlock Life Support Systems to sustain life in deep space. / / Build Starship Habitatation Modules",
    es: "Desbloquea Sistemas de Soporte Vital para mantener la vida en el espacio profundo. / / Construir Módulos de Habitación para Nave Estelar",
    pt: "Desbloqueie Sistemas de Suporte à Vida para manter a vida no espaço profundo. / / Construir Módulos de Habitação para Nave Estelar",
    de: "Schalte Lebenserhaltungssysteme frei, um Leben im Weltraum zu erhalten. / / Raumschiff-Habitat-Module bauen",
    it: "Sblocca Sistemi di Supporto Vitale per sostenere la vita nello spazio profondo. / / Costruisci Moduli Abitativi per Astronave",
    fr: "Débloque les Systèmes de Support de Vie pour soutenir la vie dans l'espace profond. / / Construire des Modules d'Habitation pour Vaisseau Stellaire",
  },
  starshipFleets: {
    en: "Unlock Starship Fleets to build and command interstellar armadas. / / Allow building of Fleet Hangar onboard the Star Ship!",
    es: "Desbloquea Flotas de Naves Estelares para construir y comandar armadas interestelares. / / Permitir construcción de Hangar de Flota en la Nave Estelar!",
    pt: "Desbloqueie Frotas de Naves Estelares para construir e comandar armadas interestelares. / / Permitir construção de Hangar de Frota na Nave Estelar!",
    de: "Schalte Raumschiffflotten frei, um interstellare Armadas zu bauen und zu kommandieren. / / Erlaube Bau des Flottenhangars an Bord des Raumschiffs!",
    it: "Sblocca Flotte di Astronavi per costruire e comandare armate interstellari. / / Permetti costruzione del Hangar della Flotta a bordo dell'Astronave!",
    fr: "Débloque les Flottes de Vaisseaux Stellaires pour construire et commander des armadas interstellaires. / / Permettre la construction du Hangar de Flotte à bord du Vaisseau Stellaire!",
  },
  stellarScanners: {
    en: "Unlock Stellar Scanners to identify life signatures around Star Systems. / / Allow building of Stellar Scanner onboard the Star Ship!",
    es: "Desbloquea Escáneres Estelares para identificar firmas de vida alrededor de Sistemas Estelares. / / Permitir construcción del Escáner Estelar a bordo de la Nave Estelar!",
    pt: "Desbloqueie Escâneres Estelares para identificar sinais de vida ao redor de Sistemas Estelares. / / Permitir construção do Escâner Estelar a bordo da Nave Estelar!",
    de: "Schalte Sternenscanner frei, um Lebenszeichen um Sternensysteme herum zu identifizieren. / / Erlaube Bau des Sternenscanners an Bord des Raumschiffs!",
    it: "Sblocca Scanner Stellari per identificare segni di vita intorno ai Sistemi Stellari. / / Permetti costruzione dello Scanner Stellare a bordo dell'Astronave!",
    fr: "Débloque les Scanners Stellaires pour identifier les signatures de vie autour des Systèmes Stellaires. / / Permettre la construction du Scanner Stellaire à bord du Vaisseau Stellaire!",
  },
  dysonSphereUnderstanding: {
    en: "Unlock Dyson Sphere Understanding to learn what a Dyson Sphere is and how it can change the course of your technological development. / /",
    es: "Desbloquea Comprensión de la Esfera de Dyson para aprender qué es una Esfera de Dyson y cómo puede cambiar el curso de tu desarrollo tecnológico. / /",
    pt: "Desbloqueie Compreensão da Esfera de Dyson para aprender o que é uma Esfera de Dyson e como ela pode mudar o rumo do seu desenvolvimento tecnológico. / /",
    de: "Schalte Dyson-Sphären-Verständnis frei, um zu lernen, was eine Dyson-Sphäre ist und wie sie den Verlauf deiner technologischen Entwicklung verändern kann. / /",
    it: "Sblocca Comprensione della Sfera di Dyson per imparare cos'è una Sfera di Dyson e come può cambiare il corso del tuo sviluppo tecnologico. / /",
    fr: "Débloque la Compréhension de la Sphère de Dyson pour apprendre ce qu'est une Sphère de Dyson et comment elle peut changer le cours de votre développement technologique. / /",
  },
  dysonSphereCapabilities: {
    en: "Unlock Dyson Sphere Capabilities to gain insight into the incredible powers and capabilities of a Dyson Sphere. / /",
    es: "Desbloquea Capacidades de la Esfera de Dyson para obtener información sobre los increíbles poderes y capacidades de una Esfera de Dyson. / /",
    pt: "Desbloqueie Capacidades da Esfera de Dyson para obter informações sobre os incríveis poderes e capacidades de uma Esfera de Dyson. / /",
    de: "Schalte Dyson-Sphären-Fähigkeiten frei, um Einblicke in die unglaublichen Kräfte und Fähigkeiten einer Dyson-Sphäre zu gewinnen. / /",
    it: "Sblocca Capacità della Sfera di Dyson per ottenere informazioni sugli incredibili poteri e capacità di una Sfera di Dyson. / /",
    fr: "Débloque les Capacités de la Sphère de Dyson pour obtenir un aperçu des pouvoirs et capacités incroyables d'une Sphère de Dyson. / /",
  },
  dysonSphereDisconnect: {
    en: "Unlock Dyson Sphere Disconnect to disconnect the Dyson Sphere from the Miaplacidus System Force Field. / /",
    es: "Desbloquea Desconexión de la Esfera de Dyson para desconectar la Esfera de Dyson del Campo de Fuerza del Sistema Miaplacidus. / /",
    pt: "Desbloqueie Desconexão da Esfera de Dyson para desconectar a Esfera de Dyson do Campo de Força do Sistema Miaplacidus. / /",
    de: "Schalte Dyson-Sphären-Trennung frei, um die Dyson-Sphäre vom Miaplacidus-System-Kraftfeld zu trennen. / /",
    it: "Sblocca Disconnessione della Sfera di Dyson per disconnettere la Sfera di Dyson dal Campo di Forza del Sistema Miaplacidus. / /",
    fr: "Débloque la Déconnexion de la Sphère de Dyson pour déconnecter la Sphère de Dyson du Champ de Force du Système Miaplacidus. / /",
  },
  dysonSpherePower: {
    en: "Unlock Dyson Sphere Power to learn how to tap into the vast energy reserves of the Dyson Sphere, powering your system and beyond. / /",
    es: "Desbloquea Energía de la Esfera de Dyson para aprender cómo aprovechar las vastas reservas de energía de la Esfera de Dyson, alimentando tu sistema y más allá. / /",
    pt: "Desbloqueie Energia da Esfera de Dyson para aprender como aproveitar as vastas reservas de energia da Esfera de Dyson, alimentando seu sistema e além. / /",
    de: "Schalte Dyson-Sphären-Energie frei, um zu lernen, wie man die riesigen Energiereserven der Dyson-Sphäre nutzt, um dein System und darüber hinaus zu versorgen. / /",
    it: "Sblocca Energia della Sfera di Dyson per imparare come sfruttare le vaste riserve di energia della Sfera di Dyson, alimentando il tuo sistema e oltre. / /",
    fr: "Débloque l'Énergie de la Sphère de Dyson pour apprendre comment exploiter les vastes réserves d'énergie de la Sphère de Dyson, alimentant votre système et au-delà. / /",
  },
  dysonSphereConnect: {
    en: "Unlock Dyson Sphere Connect to understand how to distribute the Dyson Sphere's energy across all systems, linking it to the galaxy at large. / /",
    es: "Desbloquea Conexión de la Esfera de Dyson para entender cómo distribuir la energía de la Esfera de Dyson a través de todos los sistemas, vinculándola a la galaxia en general. / /",
    pt: "Desbloqueie Conexão da Esfera de Dyson para entender como distribuir a energia da Esfera de Dyson por todos os sistemas, conectando-a à galáxia como um todo. / /",
    de: "Schalte Dyson-Sphären-Verbindung frei, um zu verstehen, wie man die Energie der Dyson-Sphäre über alle Systeme verteilt und sie mit der Galaxis verbindet. / /",
    it: "Sblocca Connessione della Sfera di Dyson per capire come distribuire l'energia della Sfera di Dyson attraverso tutti i sistemi, collegandola alla galassia nel suo insieme. / /",
    fr: "Débloque la Connexion de la Sphère de Dyson pour comprendre comment distribuer l'énergie de la Sphère de Dyson à travers tous les systèmes, la reliant à la galaxie en général. / /",
  },
  celestialProcessingCoreUnderstanding: {
    en: "Unlock Celestial Processing Core Understanding to learn what a Celestial Processing Core is and how it can revolutionize your technological infrastructure. / /",
    es: "Desbloquea Comprensión del Núcleo de Procesamiento Celestial para aprender qué es un Núcleo de Procesamiento Celestial y cómo puede revolucionar tu infraestructura tecnológica. / /",
    pt: "Desbloqueie Compreensão do Núcleo de Processamento Celestial para aprender o que é um Núcleo de Processamento Celestial e como ele pode revolucionar sua infraestrutura tecnológica. / /",
    de: "Schalte Himmlisches Verarbeitungskern-Verständnis frei, um zu lernen, was ein Himmlischer Verarbeitungskern ist und wie er deine technologische Infrastruktur revolutionieren kann. / /",
    it: "Sblocca Comprensione del Nucleo di Elaborazione Celestiale per imparare cos'è un Nucleo di Elaborazione Celestiale e come può rivoluzionare la tua infrastruttura tecnologica. / /",
    fr: "Débloque la Compréhension du Noyau de Traitement Céleste pour apprendre ce qu'est un Noyau de Traitement Céleste et comment il peut révolutionner votre infrastructure technologique. / /",
  },
  celestialProcessingCoreCapabilities: {
    en: "Unlock Celestial Processing Core Capabilities to gain insight into the immense power and functions of the Celestial Processing Core. / /",
    es: "Desbloquea Capacidades del Núcleo de Procesamiento Celestial para obtener información sobre el inmenso poder y funciones del Núcleo de Procesamiento Celestial. / /",
    pt: "Desbloqueia Capacidades do Núcleo de Processamento Celestial para obter informações sobre o imenso poder e as funções do Núcleo de Processamento Celestial. / /",
    de: "Schalte Himmlische Verarbeitungskern-Fähigkeiten frei, um Einblicke in die immense Kraft und Funktionen des Himmlischen Verarbeitungskerns zu gewinnen. / /",
    it: "Sblocca Capacità del Nucleo di Elaborazione Celestiale per ottenere informazioni sull'immenso potere e le funzioni del Nucleo di Elaborazione Celestiale. / /",
    fr: "Débloque les Capacités du Noyau de Traitement Céleste pour obtenir un aperçu de l'immense puissance et des fonctions du Noyau de Traitement Céleste. / /",
  },
  celestialProcessingCoreDisconnect: {
    en: "Unlock Celestial Processing Core Disconnect to disconnect the Celestial Processing Core from the Miaplacidus System Force Field. / /",
    es: "Desbloquea Desconexión del Núcleo de Procesamiento Celestial para desconectar el Núcleo de Procesamiento Celestial del Campo de Fuerza del Sistema Miaplacidus. / /",
    pt: "Desbloqueia Desconexão do Núcleo de Processamento Celestial para desconectar o Núcleo de Processamento Celestial do Campo de Força do Sistema Miaplacidus. / /",
    de: "Schalte Himmlische Verarbeitungskern-Trennung frei, um den Himmlischen Verarbeitungskern vom Miaplacidus-System-Kraftfeld zu trennen. / /",
    it: "Sblocca Disconnessione del Nucleo di Elaborazione Celestiale per disconnettere il Nucleo di Elaborazione Celestiale dal Campo di Forza del Sistema Miaplacidus. / /",
    fr: "Débloque la Déconnexion du Noyau de Traitement Céleste pour déconnecter le Noyau de Traitement Céleste du Champ de Force du Système Miaplacidus. / /",
  },
  celestialProcessingCorePower: {
    en: "Unlock Celestial Processing Core Power to learn how to tap into the vast power of the Celestial Processing Core, empowering your system. / /",
    es: "Desbloquea Energía del Núcleo de Procesamiento Celestial para aprender cómo aprovechar el vasto poder del Núcleo de Procesamiento Celestial, fortaleciendo tu sistema. / /",
    pt: "Desbloqueie Energia do Núcleo de Processamento Celestial para aprender como aproveitar o vasto poder do Núcleo de Processamento Celestial, fortalecendo seu sistema. / /",
    de: "Schalte Himmlische Verarbeitungskern-Energie frei, um zu lernen, wie man die riesige Kraft des Himmlischen Verarbeitungskerns nutzt, um dein System zu stärken. / /",
    it: "Sblocca Energia del Nucleo di Elaborazione Celestiale per imparare come sfruttare l'immenso potere del Nucleo di Elaborazione Celestiale, potenziando il tuo sistema. / /",
    fr: "Débloque l'Énergie du Noyau de Traitement Céleste pour apprendre comment exploiter l'immense puissance du Noyau de Traitement Céleste, renforçant votre système. / /",
  },
  celestialProcessingCoreConnect: {
    en: "Unlock Celestial Processing Core Connect to learn how to distribute the Celestial Processing Core's energy across the galaxy. / /",
    es: "Desbloquea Conexión del Núcleo de Procesamiento Celestial para aprender cómo distribuir la energía del Núcleo de Procesamiento Celestial a través de la galaxia. / /",
    pt: "Desbloqueie Conexão do Núcleo de Processamento Celestial para aprender como distribuir a energia do Núcleo de Processamento Celestial através da galáxia. / /",
    de: "Schalte Himmlische Verarbeitungskern-Verbindung frei, um zu lernen, wie man die Energie des Himmlischen Verarbeitungskerns durch die Galaxis verteilt. / /",
    it: "Sblocca Connessione del Nucleo di Elaborazione Celestiale per imparare come distribuire l'energia del Nucleo di Elaborazione Celestiale attraverso la galassia. / /",
    fr: "Débloque la Connexion du Noyau de Traitement Céleste pour apprendre comment distribuer l'énergie du Noyau de Traitement Céleste à travers la galaxie. / /",
  },
  plasmaForgeUnderstanding: {
    en: "You have studied and now understand what the MegaStructure before you is - it is a Plasma Forge / / +25% Resource AutoBuyer Rates!",
    es: "Has estudiado y ahora entiendes qué es la MegaEstructura ante ti - es una Forja de Plasma / / ¡+25% Tasas de AutoCompra de Recursos!",
    pt: "Estudaste e agora compreendes o que é a Megaestrutura diante de ti - é uma Forja de Plasma / / +25% às Taxas de Compra Automática de Recursos!",
    de: "Du hast studiert und verstehst jetzt, was die MegaStruktur vor dir ist - es ist eine Plasmaschmiede / / +25% Ressourcen-AutoKäufer-Raten!",
    it: "Hai studiato e ora capisci cos'è la MegaStruttura davanti a te - è una Forgia di Plasma / / +25% Velocità AutoAcquisto Risorse!",
    fr: "Tu as étudié et comprends maintenant ce qu'est la MégaStructure devant toi - c'est une Forge de Plasma / / +25% Taux d'AutoAchat de Ressources!",
  },
  plasmaForgeCapabilities: {
    en: "Unlock Plasma Forge Capabilities to understand the vast array of functions and capabilities that the Plasma Forge offers. / /",
    es: "Desbloquea Capacidades de la Forja de Plasma para entender la vasta gama de funciones y capacidades que ofrece la Forja de Plasma. / /",
    pt: "Desbloqueie Capacidades da Forja de Plasma para entender a vasta gama de funções e capacidades oferecidas pela Forja de Plasma. / /",
    de: "Schalte Plasma-Schmiede-Fähigkeiten frei, um die riesige Auswahl an Funktionen und Fähigkeiten zu verstehen, die die Plasma-Schmiede bietet. / /",
    it: "Sblocca Capacità della Fucina al Plasma per comprendere la vasta gamma di funzioni e capacità che la Fucina al Plasma offre. / /",
    fr: "Débloque les Capacités de la Forge de Plasma pour comprendre la vaste gamme de fonctions et capacités que la Forge de Plasma offre. / /",
  },
  plasmaForgeDisconnect: {
    en: "Unlock Plasma Forge Disconnect to disconnect the Plasma Forge from the Miaplacidus System Force Field. / /",
    es: "Desbloquea Desconexión de la Forja de Plasma para desconectar la Forja de Plasma del Campo de Fuerza del Sistema Miaplacidus. / /",
    pt: "Desbloqueie Desconexão da Forja de Plasma para desconectar a Forja de Plasma do Campo de Força do Sistema Miaplacidus. / /",
    de: "Schalte Plasma-Schmiede-Trennung frei, um die Plasma-Schmiede vom Miaplacidus-System-Kraftfeld zu trennen. / /",
    it: "Sblocca Disconnessione della Fucina al Plasma per disconnettere la Fucina al Plasma dal Campo di Forza del Sistema Miaplacidus. / /",
    fr: "Débloque la Déconnexion de la Forge de Plasma pour déconnecter la Forge de Plasma du Champ de Force du Système Miaplacidus. / /",
  },
  plasmaForgePower: {
    en: "Unlock Plasma Forge Power to learn how to utilize the immense energy of the Plasma Forge for powering your system. / /",
    es: "Desbloquea Energía de la Forja de Plasma para aprender cómo utilizar la inmensa energía de la Forja de Plasma para alimentar tu sistema. / /",
    pt: "Desbloqueie Energia da Forja de Plasma para aprender como utilizar a imensa energia da Forja de Plasma para alimentar seu sistema. / /",
    de: "Schalte Plasma-Schmiede-Energie frei, um zu lernen, wie man die immense Energie der Plasma-Schmiede nutzt, um dein System zu versorgen. / /",
    it: "Sblocca Energia della Fucina al Plasma per imparare come utilizzare l'immenso energia della Fucina al Plasma per alimentare il tuo sistema. / /",
    fr: "Débloque l'Énergie de la Forge de Plasma pour apprendre comment utiliser l'immense énergie de la Forge de Plasma pour alimenter votre système. / /",
  },
  plasmaForgeConnect: {
    en: "Unlock Plasma Forge Connect to learn how to extend the Plasma Forge's energy across multiple systems, expanding your reach. / /",
    es: "Desbloquea Conexión de la Forja de Plasma para aprender cómo extender la energía de la Forja de Plasma a través de múltiples sistemas, expandiendo tu alcance. / /",
    pt: "Desbloqueie Conexão da Forja de Plasma para aprender como estender a energia da Forja de Plasma através de múltiplos sistemas, expandindo seu alcance. / /",
    de: "Schalte Plasma-Schmiede-Verbindung frei, um zu lernen, wie man die Energie der Plasma-Schmiede über mehrere Systeme ausdehnt und deine Reichweite erweitert. / /",
    it: "Sblocca Connessione della Fucina al Plasma per imparare come estendere l'energia della Fucina al Plasma attraverso molteplici sistemi, espandendo la tua portata. / /",
    fr: "Débloque la Connexion de la Forge de Plasma pour apprendre comment étendre l'énergie de la Forge de Plasma à travers plusieurs systèmes, élargissant votre portée. / /",
  },
  galacticMemoryArchiveUnderstanding: {
    en: "Unlock Galactic Memory Archive Understanding to understand what the Galactic Memory Archive is and how it holds vital cosmic data. / /",
    es: "Desbloquea Comprensión del Archivo de Memoria Galáctica para entender qué es el Archivo de Memoria Galáctica y cómo contiene datos cósmicos vitales. / /",
    pt: "Desbloqueie Compreensão do Arquivo de Memória Galáctica para entender o que é o Arquivo de Memória Galáctica e como ele contém dados cósmicos vitais. / /",
    de: "Schalte Galaktisches Gedächtnisarchiv-Verständnis frei, um zu verstehen, was das Galaktische Gedächtnisarchiv ist und wie es wichtige kosmische Daten enthält. / /",
    it: "Sblocca Comprensione dell'Archivio di Memoria Galattica per capire cos'è l'Archivio di Memoria Galattica e come contiene dati cosmici vitali. / /",
    fr: "Débloque la Compréhension de l'Archive de Mémoire Galactique pour comprendre ce qu'est l'Archive de Mémoire Galactique et comment elle détient des données cosmiques vitales. / /",
  },
  galacticMemoryArchiveCapabilities: {
    en: "Unlock Galactic Memory Archive Capabilities to discover the powerful functions and capabilities that the Galactic Memory Archive holds. / /",
    es: "Desbloquea Capacidades del Archivo de Memoria Galáctica para descubrir las poderosas funciones y capacidades que posee el Archivo de Memoria Galáctica. / /",
    pt: "Desbloqueie Capacidades do Arquivo de Memória Galáctica para descobrir as poderosas funções e capacidades que o Arquivo de Memória Galáctica possui. / /",
    de: "Schalte Galaktisches Gedächtnisarchiv-Fähigkeiten frei, um die mächtigen Funktionen und Fähigkeiten zu entdecken, die das Galaktische Gedächtnisarchiv birgt. / /",
    it: "Sblocca Capacità dell'Archivio di Memoria Galattica per scoprire le potenti funzioni e capacità che l'Archivio di Memoria Galattica possiede. / /",
    fr: "Débloque les Capacités de l'Archive de Mémoire Galactique pour découvrir les fonctions puissantes et capacités que l'Archive de Mémoire Galactique détient. / /",
  },
  galacticMemoryArchiveDisconnect: {
    en: "Unlock Galactic Memory Archive Disconnect to disconnect the Galactic Memory Archive from the Miaplacidus System Force Field. / /",
    es: "Desbloquea Desconexión del Archivo de Memoria Galáctica para desconectar el Archivo de Memoria Galáctica del Campo de Fuerza del Sistema Miaplacidus. / /",
    pt: "Desbloqueie Desconexão do Arquivo de Memória Galáctica para desconectar o Arquivo de Memória Galáctica do Campo de Força do Sistema Miaplacidus. / /",
    de: "Schalte Galaktisches Gedächtnisarchiv-Trennung frei, um das Galaktische Gedächtnisarchiv vom Miaplacidus-System-Kraftfeld zu trennen. / /",
    it: "Sblocca Disconnessione dell'Archivio di Memoria Galattica per disconnettere l'Archivio di Memoria Galattica dal Campo di Forza del Sistema Miaplacidus. / /",
    fr: "Débloque la Déconnexion de l'Archive de Mémoire Galactique pour déconnecter l'Archive de Mémoire Galactique du Champ de Force du Système Miaplacidus. / /",
  },
  galacticMemoryArchivePower: {
    en: "Unlock Galactic Memory Archive Power to tap into the cosmic energy stored in the Galactic Memory Archive for your system's benefit. / /",
    es: "Desbloquea Energía del Archivo de Memoria Galáctica para aprovechar la energía cósmica almacenada en el Archivo de Memoria Galáctica para beneficio de tu sistema. / /",
    pt: "Desbloqueie Energia do Arquivo de Memória Galáctica para aproveitar a energia cósmica armazenada no Arquivo de Memória Galáctica para benefício do seu sistema. / /",
    de: "Schalte Galaktisches Gedächtnisarchiv-Energie frei, um die kosmische Energie zu nutzen, die im Galaktischen Gedächtnisarchiv für den Nutzen deines Systems gespeichert ist. / /",
    it: "Sblocca Energia dell'Archivio di Memoria Galattica per attingere all'energia cosmica immagazzinata nell'Archivio di Memoria Galattica per il beneficio del tuo sistema. / /",
    fr: "Débloque l'Énergie de l'Archive de Mémoire Galactique pour exploiter l'énergie cosmique stockée dans l'Archive de Mémoire Galactique pour le bénéfice de votre système. / /",
  },
  galacticMemoryArchiveConnect: {
    en: "Unlock Galactic Memory Archive Connect to connect the Galactic Memory Archive's energy across all systems, extending your technological network. / /",
    es: "Desbloquea Conexión del Archivo de Memoria Galáctica para conectar la energía del Archivo de Memoria Galáctica a través de todos los sistemas, extendiendo tu red tecnológica. / /",
    pt: "Desbloqueie Conexão do Arquivo de Memória Galáctica para conectar a energia do Arquivo de Memória Galáctica através de todos os sistemas, expandindo sua rede tecnológica. / /",
    de: "Schalte Galaktisches Gedächtnisarchiv-Verbindung frei, um die Energie des Galaktischen Gedächtnisarchivs über alle Systeme zu verbinden und dein technologisches Netzwerk zu erweitern. / /",
    it: "Sblocca Connessione dell'Archivio di Memoria Galattica per collegare l'energia dell'Archivio di Memoria Galattica attraverso tutti i sistemi, estendendo la tua rete tecnologica. / /",
    fr: "Débloque la Connexion de l'Archive de Mémoire Galactique pour connecter l'énergie de l'Archive de Mémoire Galactique à travers tous les systèmes, étendant votre réseau technologique. / /",
  },
} as const satisfies Readonly<Record<TechId, Readonly<Record<LocaleId, string>>>>;
