import type { LocaleId, TechId } from "./ids";

export const TECHNOLOGY_NAMES = {
  knowledgeSharing: {
    en: "Knowledge Sharing",
    es: "Intercambio de Conocimiento",
    pt: "Partilha de Conhecimento",
    de: "Wissensaustausch",
    it: "Condivisione della Conoscenza",
    fr: "Partage des Connaissances",
  },
  fusionTheory: {
    en: "Fusion Theory",
    es: "Teoría de la Fusión",
    pt: "Teoria da Fusão",
    de: "Fusionstheorie",
    it: "Teoria della Fusione",
    fr: "Théorie de la Fusion",
  },
  hydrogenFusion: {
    en: "Hydrogen Fusion",
    es: "Fusión de Hidrógeno",
    pt: "Fusão de Hidrogénio",
    de: "Wasserstofffusion",
    it: "Fusione dell'Idrogeno",
    fr: "Fusion de l'Hydrogène",
  },
  heliumFusion: {
    en: "Helium Fusion",
    es: "Fusión de Helio",
    pt: "Fusão de Hélio",
    de: "Heliumfusion",
    it: "Fusione dell'Elio",
    fr: "Fusion de l'Hélium",
  },
  carbonFusion: {
    en: "Carbon Fusion",
    es: "Fusión de Carbono",
    pt: "Fusão de Carbono",
    de: "Kohlenstofffusion",
    it: "Fusione del Carbonio",
    fr: "Fusion du Carbone",
  },
  basicPowerGeneration: {
    en: "Basic Power Generation",
    es: "Generación Básica de Energía",
    pt: "Geração Básica de Energia",
    de: "Einfache Energieerzeugung",
    it: "Generazione Elettrica di Base",
    fr: "Production d'Énergie de Base",
  },
  sodiumIonPowerStorage: {
    en: "Sodium Ion Power Storage",
    es: "Almacenamiento de Energía de Iones de Sodio",
    pt: "Armazenamento de Energia de Iões de Sódio",
    de: "Natrium-Ionen-Energiespeicher",
    it: "Accumulo Energetico agli Ioni di Sodio",
    fr: "Stockage d'Énergie Sodium-Ion",
  },
  solarPowerGeneration: {
    en: "Solar Power Generation",
    es: "Generación de Energía Solar",
    pt: "Geração de Energia Solar",
    de: "Solarenergieerzeugung",
    it: "Generazione di Energia Solare",
    fr: "Production d'Énergie Solaire",
  },
  giganticTurbines: {
    en: "Gigantic Turbines",
    es: "Turbinas Gigantescas",
    pt: "Turbinas Gigantescas",
    de: "Gigantische Turbinen",
    it: "Turbine Giganti",
    fr: "Turbines Géantes",
  },
  advancedPowerGeneration: {
    en: "Advanced Power Generation",
    es: "Generación Avanzada de Energía",
    pt: "Geração Avançada de Energia",
    de: "Fortgeschrittene Energieerzeugung",
    it: "Generazione Elettrica Avanzata",
    fr: "Production d'Énergie Avancée",
  },
  rocketComposites: {
    en: "Rocket Composites",
    es: "Compuestos para Cohetes",
    pt: "Compósitos para Foguetões",
    de: "Raketenverbundstoffe",
    it: "Compositi per Razzi",
    fr: "Composites pour Fusées",
  },
  advancedFuels: {
    en: "Advanced Fuels",
    es: "Combustibles Avanzados",
    pt: "Combustíveis Avançados",
    de: "Fortschrittliche Treibstoffe",
    it: "Carburanti Avanzati",
    fr: "Carburants Avancés",
  },
  planetaryNavigation: {
    en: "Planetary Navigation",
    es: "Navegación Planetaria",
    pt: "Navegação Planetária",
    de: "Planetare Navigation",
    it: "Navigazione Planetaria",
    fr: "Navigation Planétaire",
  },
  neonFusion: {
    en: "Neon Fusion",
    es: "Fusión de Neón",
    pt: "Fusão de Néon",
    de: "Neonfusion",
    it: "Fusione del Neon",
    fr: "Fusion du Néon",
  },
  oxygenFusion: {
    en: "Oxygen Fusion",
    es: "Fusión de Oxígeno",
    pt: "Fusão de Oxigénio",
    de: "Sauerstofffusion",
    it: "Fusione dell'Ossigeno",
    fr: "Fusion de l'Oxygène",
  },
  compounds: {
    en: "Compounds",
    es: "Compuestos",
    pt: "Compostos",
    de: "Verbindungen",
    it: "Composti",
    fr: "Composés",
  },
  siliconFusion: {
    en: "Silicon Fusion",
    es: "Fusión de Silicio",
    pt: "Fusão de Silício",
    de: "Siliziumfusion",
    it: "Fusione del Silicio",
    fr: "Fusion du Silicium",
  },
  aggregateMixing: {
    en: "Aggregate Mixing",
    es: "Mezcla de Áridos",
    pt: "Mistura de Agregados",
    de: "Zuschlagstoffmischung",
    it: "Miscelazione degli Inerti",
    fr: "Mélange des Granulats",
  },
  steelFoundries: {
    en: "Steel Foundries",
    es: "Fundiciones de Acero",
    pt: "Fundições de Aço",
    de: "Stahlgießereien",
    it: "Fonderie d'Acciaio",
    fr: "Fonderies d'Acier",
  },
  nanoTubeTechnology: {
    en: "Nano Tube Technology",
    es: "Tecnología de Nanotubos",
    pt: "Tecnologia de Nanotubos",
    de: "Nanoröhrchen-Technologie",
    it: "Tecnologia dei Nanotubi",
    fr: "Technologie des Nanotubes",
  },
  hydroCarbons: {
    en: "HydroCarbons",
    es: "Hidrocarburos",
    pt: "Hidrocarbonetos",
    de: "Kohlenwasserstoffe",
    it: "Idrocarburi",
    fr: "Hydrocarbures",
  },
  stellarCartography: {
    en: "Stellar Cartography",
    es: "Cartografía Estelar",
    pt: "Cartografia Estelar",
    de: "Sternenkartografie",
    it: "Cartografia Stellare",
    fr: "Cartographie Stellaire",
  },
  quantumComputing: {
    en: "Quantum Computing",
    es: "Computación Cuántica",
    pt: "Computação Quântica",
    de: "Quantencomputing",
    it: "Informatica Quantistica",
    fr: "Informatique Quantique",
  },
  scienceLaboratories: {
    en: "Science Laboratories",
    es: "Laboratorios Científicos",
    pt: "Laboratórios Científicos",
    de: "Wissenschaftslabore",
    it: "Laboratori Scientifici",
    fr: "Laboratoires Scientifiques",
  },
  nobleGasCollection: {
    en: "Noble Gas Collection",
    es: "Recolección de Gases Nobles",
    pt: "Recolha de Gases Nobres",
    de: "Edelgassammlung",
    it: "Raccolta di Gas Nobili",
    fr: "Collecte de Gaz Nobles",
  },
  neutronCapture: {
    en: "Neutron Capture",
    es: "Captura de Neutrones",
    pt: "Captura de Neutrões",
    de: "Neutroneneinfang",
    it: "Cattura Neutronica",
    fr: "Capture de Neutrons",
  },
  glassManufacture: {
    en: "Glass Manufacture",
    es: "Fabricación de Vidrio",
    pt: "Fabrico de Vidro",
    de: "Glasherstellung",
    it: "Produzione del Vetro",
    fr: "Fabrication du Verre",
  },
  atmosphericTelescopes: {
    en: "Atmospheric Telescopes",
    es: "Telescopios Atmosféricos",
    pt: "Telescópios Atmosféricos",
    de: "Atmosphärische Teleskope",
    it: "Telescopi Atmosferici",
    fr: "Télescopes Atmosphériques",
  },
  fusionEfficiencyI: {
    en: "Fusion Efficiency I",
    es: "Eficiencia de Fusión I",
    pt: "Eficiência de Fusão I",
    de: "Fusionseffizienz I",
    it: "Efficienza di Fusione I",
    fr: "Efficacité de Fusion I",
  },
  fusionEfficiencyII: {
    en: "Fusion Efficiency II",
    es: "Eficiencia de Fusión II",
    pt: "Eficiência de Fusão II",
    de: "Fusionseffizienz II",
    it: "Efficienza di Fusione II",
    fr: "Efficacité de Fusion II",
  },
  fusionEfficiencyIII: {
    en: "Fusion Efficiency III",
    es: "Eficiencia de Fusión III",
    pt: "Eficiência de Fusão III",
    de: "Fusionseffizienz III",
    it: "Efficienza di Fusione III",
    fr: "Efficacité de Fusion III",
  },
  orbitalConstruction: {
    en: "Orbital Construction",
    es: "Construcción Orbital",
    pt: "Construção Orbital",
    de: "Orbitalbau",
    it: "Costruzione Orbitale",
    fr: "Construction Orbitale",
  },
  antimatterEngines: {
    en: "Antimatter Engines",
    es: "Motores de Antimateria",
    pt: "Motores de Antimatéria",
    de: "Antimaterie-Triebwerke",
    it: "Motori ad Antimateria",
    fr: "Moteurs à Antimatière",
  },
  FTLTravelTheory: {
    en: "FTL Travel Theory",
    es: "Teoría del Viaje FTL",
    pt: "Teoria da Viagem FTL",
    de: "Theorie der Überlichtreise",
    it: "Teoria del Viaggio FTL",
    fr: "Théorie du Voyage FTL",
  },
  lifeSupportSystems: {
    en: "Life Support Systems",
    es: "Sistemas de Soporte Vital",
    pt: "Sistemas de Suporte de Vida",
    de: "Lebenserhaltungssysteme",
    it: "Sistemi di Supporto Vitale",
    fr: "Systèmes de Survie",
  },
  starshipFleets: {
    en: "Starship Fleets",
    es: "Flotas de Naves Estelares",
    pt: "Frotas de Naves Estelares",
    de: "Sternenschiffflotten",
    it: "Flotte di Astronavi",
    fr: "Flottes de Vaisseaux Stellaires",
  },
  stellarScanners: {
    en: "Stellar Scanners",
    es: "Escáneres Estelares",
    pt: "Scanners Estelares",
    de: "Stellarscanner",
    it: "Scanner Stellari",
    fr: "Scanners Stellaires",
  },
  dysonSphereUnderstanding: {
    en: "Dyson Sphere Understanding",
    es: "Comprensión de la Esfera de Dyson",
    pt: "Compreensão da Esfera de Dyson",
    de: "Dyson-Sphären-Verständnis",
    it: "Comprensione della Sfera di Dyson",
    fr: "Compréhension de la Sphère de Dyson",
  },
  dysonSphereCapabilities: {
    en: "Dyson Sphere Capabilities",
    es: "Capacidades de la Esfera de Dyson",
    pt: "Capacidades da Esfera de Dyson",
    de: "Dyson-Sphären-Fähigkeiten",
    it: "Capacità della Sfera di Dyson",
    fr: "Capacités de la Sphère de Dyson",
  },
  dysonSphereDisconnect: {
    en: "Dyson Sphere Disconnect",
    es: "Desconexión de la Esfera de Dyson",
    pt: "Desconexão da Esfera de Dyson",
    de: "Dyson-Sphären-Trennung",
    it: "Disconnessione della Sfera di Dyson",
    fr: "Déconnexion de la Sphère de Dyson",
  },
  dysonSpherePower: {
    en: "Dyson Sphere Power",
    es: "Poder de la Esfera de Dyson",
    pt: "Poder da Esfera de Dyson",
    de: "Dyson-Sphären-Energie",
    it: "Potere della Sfera di Dyson",
    fr: "Puissance de la Sphère de Dyson",
  },
  dysonSphereConnect: {
    en: "Dyson Sphere Connect",
    es: "Conexión de la Esfera de Dyson",
    pt: "Conexão da Esfera de Dyson",
    de: "Dyson-Sphären-Verbindung",
    it: "Connessione della Sfera di Dyson",
    fr: "Connexion de la Sphère de Dyson",
  },
  celestialProcessingCoreUnderstanding: {
    en: "CPC Understanding",
    es: "Comprensión del NPC",
    pt: "Compreensão do NPC",
    de: "NPC-Verständnis",
    it: "Comprensione del NDC",
    fr: "Compréhension du NTC",
  },
  celestialProcessingCoreCapabilities: {
    en: "CPC Capabilities",
    es: "Capacidades del NPC",
    pt: "Capacidades do NPC",
    de: "NPC-Fähigkeiten",
    it: "Capacità del NDC",
    fr: "Capacités du NTC",
  },
  celestialProcessingCoreDisconnect: {
    en: "CPC Disconnect",
    es: "Desconexión del NPC",
    pt: "Desconexão do NPC",
    de: "NPC-Trennung",
    it: "Disconnessione del NDC",
    fr: "Déconnexion du NTC",
  },
  celestialProcessingCorePower: {
    en: "CPC Power",
    es: "Poder del NPC",
    pt: "Poder do NPC",
    de: "NPC-Energie",
    it: "Potere del NDC",
    fr: "Puissance du NTC",
  },
  celestialProcessingCoreConnect: {
    en: "CPC Connect",
    es: "Conexión del NPC",
    pt: "Conexão do NPC",
    de: "NPC-Verbindung",
    it: "Connessione del NDC",
    fr: "Connexion du NTC",
  },
  plasmaForgeUnderstanding: {
    en: "Plasma Forge Understanding",
    es: "Comprensión de la Forja de Plasma",
    pt: "Compreensão da Forja de Plasma",
    de: "Plasmaschmieden-Verständnis",
    it: "Comprensione della Forgia al Plasma",
    fr: "Compréhension de la Forge de Plasma",
  },
  plasmaForgeCapabilities: {
    en: "Plasma Forge Capabilities",
    es: "Capacidades de la Forja de Plasma",
    pt: "Capacidades da Forja de Plasma",
    de: "Plasmaschmieden-Fähigkeiten",
    it: "Capacità della Forgia al Plasma",
    fr: "Capacités de la Forge de Plasma",
  },
  plasmaForgeDisconnect: {
    en: "Plasma Forge Disconnect",
    es: "Desconexión de la Forja de Plasma",
    pt: "Desconexão da Forja de Plasma",
    de: "Plasmaschmieden-Trennung",
    it: "Disconnessione della Forgia al Plasma",
    fr: "Déconnexion de la Forge de Plasma",
  },
  plasmaForgePower: {
    en: "Plasma Forge Power",
    es: "Poder de la Forja de Plasma",
    pt: "Poder da Forja de Plasma",
    de: "Plasmaschmieden-Energie",
    it: "Potere della Forgia al Plasma",
    fr: "Puissance de la Forge de Plasma",
  },
  plasmaForgeConnect: {
    en: "Plasma Forge Connect",
    es: "Conexión de la Forja de Plasma",
    pt: "Conexão da Forja de Plasma",
    de: "Plasmaschmieden-Verbindung",
    it: "Connessione della Forgia al Plasma",
    fr: "Connexion de la Forge de Plasma",
  },
  galacticMemoryArchiveUnderstanding: {
    en: "GMA Understanding",
    es: "Comprensión del AMG",
    pt: "Compreensão do AMG",
    de: "AMG-Verständnis",
    it: "Comprensione dell AMG",
    fr: "Compréhension de l AMG",
  },
  galacticMemoryArchiveCapabilities: {
    en: "GMA Capabilities",
    es: "Capacidades del AMG",
    pt: "Capacidades do AMG",
    de: "AMG-Fähigkeiten",
    it: "Capacità dell AMG",
    fr: "Capacités de l AMG",
  },
  galacticMemoryArchiveDisconnect: {
    en: "GMA Disconnect",
    es: "Desconexión del AMG",
    pt: "Desconexão do AMG",
    de: "AMG-Trennung",
    it: "Disconnessione dell AMG",
    fr: "Déconnexion de l AMG",
  },
  galacticMemoryArchivePower: {
    en: "GMA Power",
    es: "Poder del AMG",
    pt: "Poder do AMG",
    de: "AMG-Energie",
    it: "Potere dell AMG",
    fr: "Puissance de l AMG",
  },
  galacticMemoryArchiveConnect: {
    en: "GMA Connect",
    es: "Conexión del AMG",
    pt: "Conexão do AMG",
    de: "AMG-Verbindung",
    it: "Connessione dell AMG",
    fr: "Connexion de l AMG",
  },
} as const satisfies Readonly<Record<TechId, Readonly<Record<LocaleId, string>>>>;
