import type { TechId } from "./ids";

export interface TechnologyDefinition {
  readonly id: TechId;
  readonly path: number;
  readonly renderPosition: number;
  readonly price: number;
  readonly revealThreshold: number;
  readonly requires: readonly TechId[];
  readonly effectSummary: string;
  readonly special?: "megastructure";
}

export const MEGASTRUCTURE_IDS = [
  "dysonSphere",
  "celestialProcessingCore",
  "plasmaForge",
  "galacticMemoryArchive",
] as const;
export type MegastructureId = (typeof MEGASTRUCTURE_IDS)[number];

/** The original game researches these 20 stages as four independent, ordered tracks. */
export const MEGASTRUCTURE_TRACKS: Readonly<Record<MegastructureId, readonly TechId[]>> = {
  dysonSphere: [
    "dysonSphereUnderstanding",
    "dysonSphereCapabilities",
    "dysonSphereDisconnect",
    "dysonSpherePower",
    "dysonSphereConnect",
  ],
  celestialProcessingCore: [
    "celestialProcessingCoreUnderstanding",
    "celestialProcessingCoreCapabilities",
    "celestialProcessingCoreDisconnect",
    "celestialProcessingCorePower",
    "celestialProcessingCoreConnect",
  ],
  plasmaForge: [
    "plasmaForgeUnderstanding",
    "plasmaForgeCapabilities",
    "plasmaForgeDisconnect",
    "plasmaForgePower",
    "plasmaForgeConnect",
  ],
  galacticMemoryArchive: [
    "galacticMemoryArchiveUnderstanding",
    "galacticMemoryArchiveCapabilities",
    "galacticMemoryArchiveDisconnect",
    "galacticMemoryArchivePower",
    "galacticMemoryArchiveConnect",
  ],
};
export const MEGASTRUCTURE_TECHNOLOGY_IDS = Object.values(MEGASTRUCTURE_TRACKS).flat();

/** Source-backed catalogue extracted from docs/audit/foundation-economy.md. */
export const TECHNOLOGY_CATALOG = [
  {
    id: "knowledgeSharing",
    path: 1,
    renderPosition: 10,
    price: 150,
    revealThreshold: 0,
    requires: [],
    effectSummary:
      "Opens Research progression; enables Science Club; first-run Research-tab modal.",
  },
  {
    id: "fusionTheory",
    path: 1,
    renderPosition: 20,
    price: 750,
    revealThreshold: 500,
    requires: ["knowledgeSharing"],
    effectSummary: "Opens Hydrogen Fusion research path.",
  },
  {
    id: "hydrogenFusion",
    path: 1,
    renderPosition: 30,
    price: 1150,
    revealThreshold: 1000,
    requires: ["fusionTheory"],
    effectSummary: "Enables Hydrogen fusion; first discovered output is Helium.",
  },
  {
    id: "heliumFusion",
    path: 1,
    renderPosition: 40,
    price: 2300,
    revealThreshold: 2000,
    requires: ["hydrogenFusion"],
    effectSummary: "Enables Helium fusion; path to Carbon.",
  },
  {
    id: "carbonFusion",
    path: 1,
    renderPosition: 50,
    price: 4300,
    revealThreshold: 4100,
    requires: ["nobleGasCollection"],
    effectSummary: "Enables Carbon fusion; Carbon has Neon and Sodium outputs.",
  },
  {
    id: "basicPowerGeneration",
    path: 2,
    renderPosition: 51,
    price: 4200,
    revealThreshold: 3000,
    requires: ["heliumFusion"],
    effectSummary: "Unlocks Energy tab and Plant 1.",
  },
  {
    id: "sodiumIonPowerStorage",
    path: 2,
    renderPosition: 52,
    price: 7000,
    revealThreshold: 5000,
    requires: ["basicPowerGeneration"],
    effectSummary: "Unlocks Battery 1 and battery status information.",
  },
  {
    id: "solarPowerGeneration",
    path: 2,
    renderPosition: 53,
    price: 15000,
    revealThreshold: 12000,
    requires: ["steelFoundries", "glassManufacture"],
    effectSummary: "Unlocks Solar Power Plant.",
  },
  {
    id: "giganticTurbines",
    path: 2,
    renderPosition: 54,
    price: 4800,
    revealThreshold: 4200,
    requires: ["hydroCarbons"],
    effectSummary:
      "Prerequisite for Advanced Power Generation; no separate runtime mutation was found in its purchase switch.",
  },
  {
    id: "advancedPowerGeneration",
    path: 2,
    renderPosition: 55,
    price: 8000,
    revealThreshold: 6000,
    requires: ["giganticTurbines", "basicPowerGeneration"],
    effectSummary: "Unlocks Plant 3 and Battery 2.",
  },
  {
    id: "rocketComposites",
    path: 5,
    renderPosition: 56,
    price: 34000,
    revealThreshold: 28000,
    requires: ["neutronCapture", "nanoTubeTechnology", "steelFoundries"],
    effectSummary: "Reveals Launch Pad and sets normal-progression resource autobuyers to tier 4.",
  },
  {
    id: "advancedFuels",
    path: 2,
    renderPosition: 57,
    price: 30000,
    revealThreshold: 25000,
    requires: ["hydroCarbons", "neutronCapture", "advancedPowerGeneration"],
    effectSummary: "Enables rocket fueling.",
  },
  {
    id: "planetaryNavigation",
    path: 5,
    renderPosition: 58,
    price: 29000,
    revealThreshold: 27000,
    requires: ["atmosphericTelescopes", "rocketComposites", "quantumComputing"],
    effectSummary: "Enables travel to asteroids.",
  },
  {
    id: "neonFusion",
    path: 1,
    renderPosition: 60,
    price: 5750,
    revealThreshold: 5000,
    requires: ["carbonFusion"],
    effectSummary: "Enables Neon fusion; unlocks Water compound.",
  },
  {
    id: "oxygenFusion",
    path: 1,
    renderPosition: 70,
    price: 8000,
    revealThreshold: 7000,
    requires: ["neonFusion"],
    effectSummary: "Enables Oxygen fusion; path to Silicon.",
  },
  {
    id: "compounds",
    path: 1,
    renderPosition: 75,
    price: 9000,
    revealThreshold: 8000,
    requires: ["hydrogenFusion", "carbonFusion"],
    effectSummary: "Opens Compounds pane.",
  },
  {
    id: "siliconFusion",
    path: 1,
    renderPosition: 80,
    price: 11500,
    revealThreshold: 10000,
    requires: ["oxygenFusion"],
    effectSummary: "Enables Silicon fusion; path to Iron.",
  },
  {
    id: "aggregateMixing",
    path: 1,
    renderPosition: 81,
    price: 13000,
    revealThreshold: 12000,
    requires: ["siliconFusion"],
    effectSummary: "Unlocks Concrete.",
  },
  {
    id: "steelFoundries",
    path: 1,
    renderPosition: 82,
    price: 13000,
    revealThreshold: 11500,
    requires: ["siliconFusion"],
    effectSummary: "Unlocks Steel.",
  },
  {
    id: "nanoTubeTechnology",
    path: 4,
    renderPosition: 499,
    price: 4000,
    revealThreshold: 3500,
    requires: ["heliumFusion"],
    effectSummary:
      "Prerequisite for Noble Gas Collection, Quantum Computing and other later systems; no direct economy mutation in the purchase switch.",
  },
  {
    id: "hydroCarbons",
    path: 2,
    renderPosition: 500,
    price: 3800,
    revealThreshold: 3200,
    requires: ["basicPowerGeneration"],
    effectSummary: "Unlocks Diesel.",
  },
  {
    id: "stellarCartography",
    path: 4,
    renderPosition: 510,
    price: 800,
    revealThreshold: 700,
    requires: [],
    effectSummary: "Unlocks Star Map; first-run Interstellar-tab modal.",
  },
  {
    id: "quantumComputing",
    path: 4,
    renderPosition: 520,
    price: 5750,
    revealThreshold: 3500,
    requires: ["nanoTubeTechnology"],
    effectSummary: "Sets normal-progression resource autobuyers to tier 2; first-run unlock modal.",
  },
  {
    id: "scienceLaboratories",
    path: 4,
    renderPosition: 521,
    price: 7000,
    revealThreshold: 5750,
    requires: ["quantumComputing"],
    effectSummary: "Unlocks Science Lab; first-run Research-tab modal.",
  },
  {
    id: "nobleGasCollection",
    path: 4,
    renderPosition: 530,
    price: 4500,
    revealThreshold: 4000,
    requires: ["nanoTubeTechnology"],
    effectSummary: "Required before Carbon Fusion; no separate purchase-switch mutation.",
  },
  {
    id: "neutronCapture",
    path: 5,
    renderPosition: 600,
    price: 23000,
    revealThreshold: 20000,
    requires: ["siliconFusion"],
    effectSummary: "Unlocks Titanium compound.",
  },
  {
    id: "glassManufacture",
    path: 4,
    renderPosition: 700,
    price: 9000,
    revealThreshold: 8000,
    requires: ["oxygenFusion"],
    effectSummary: "Unlocks Glass.",
  },
  {
    id: "atmosphericTelescopes",
    path: 4,
    renderPosition: 750,
    price: 10000,
    revealThreshold: 9000,
    requires: ["glassManufacture", "stellarCartography"],
    effectSummary: "Reveals Space Telescope and first-run Space Mining-tab modal.",
  },
  {
    id: "fusionEfficiencyI",
    path: 10,
    renderPosition: 9000,
    price: 1750,
    revealThreshold: 1500,
    requires: ["fusionTheory"],
    effectSummary: "Raises subsequent fusion yield range from 20–30% to 40–60%.",
  },
  {
    id: "fusionEfficiencyII",
    path: 10,
    renderPosition: 9010,
    price: 3500,
    revealThreshold: 3000,
    requires: ["fusionEfficiencyI"],
    effectSummary: "Raises yield range to 60–80%.",
  },
  {
    id: "fusionEfficiencyIII",
    path: 10,
    renderPosition: 9030,
    price: 10000,
    revealThreshold: 9000,
    requires: ["fusionEfficiencyII"],
    effectSummary: "Sets fusion yield to 100%.",
  },
  {
    id: "orbitalConstruction",
    path: 5,
    renderPosition: 9100,
    price: 50000,
    revealThreshold: 45000,
    requires: ["planetaryNavigation", "rocketComposites"],
    effectSummary: "Reveals Star Ship pane; also gates Battery 3.",
  },
  {
    id: "antimatterEngines",
    path: 5,
    renderPosition: 9101,
    price: 78000,
    revealThreshold: 65000,
    requires: ["orbitalConstruction", "neutronCapture", "FTLTravelTheory"],
    effectSummary: "Unlocks antimatter starship engine module.",
  },
  {
    id: "FTLTravelTheory",
    path: 5,
    renderPosition: 9102,
    price: 65000,
    revealThreshold: 60000,
    requires: ["neutronCapture", "planetaryNavigation", "advancedFuels"],
    effectSummary: "Enables FTL travel.",
  },
  {
    id: "lifeSupportSystems",
    path: 5,
    renderPosition: 9103,
    price: 60000,
    revealThreshold: 55000,
    requires: ["orbitalConstruction", "nanoTubeTechnology", "quantumComputing"],
    effectSummary: "Unlocks Life Support starship module.",
  },
  {
    id: "starshipFleets",
    path: 5,
    renderPosition: 9104,
    price: 100000,
    revealThreshold: 80000,
    requires: ["FTLTravelTheory", "antimatterEngines", "orbitalConstruction"],
    effectSummary: "Unlocks starship fleet hangar.",
  },
  {
    id: "stellarScanners",
    path: 5,
    renderPosition: 9105,
    price: 72000,
    revealThreshold: 70000,
    requires: ["FTLTravelTheory", "orbitalConstruction"],
    effectSummary: "Unlocks Stellar Scanners.",
  },
  {
    id: "dysonSphereUnderstanding",
    path: 6,
    renderPosition: 10001,
    price: 50000,
    revealThreshold: 40000,
    requires: ["advancedPowerGeneration"],
    effectSummary:
      "Dyson stage 1: doubles each battery template capacity and current energy capacity.",
    special: "megastructure",
  },
  {
    id: "dysonSphereCapabilities",
    path: 6,
    renderPosition: 10002,
    price: 100000,
    revealThreshold: 80000,
    requires: ["dysonSphereUnderstanding"],
    effectSummary: "Dyson stage 2: ×1.25 to each power plant’s rate/max and purchased rate.",
    special: "megastructure",
  },
  {
    id: "dysonSphereDisconnect",
    path: 6,
    renderPosition: 10003,
    price: 150000,
    revealThreshold: 120000,
    requires: ["dysonSphereCapabilities"],
    effectSummary:
      "Dyson stage 3: grants 0.15 antimatter milestone and permanent antimatter unlock.",
    special: "megastructure",
  },
  {
    id: "dysonSpherePower",
    path: 6,
    renderPosition: 10004,
    price: 200000,
    revealThreshold: 160000,
    requires: ["dysonSphereDisconnect"],
    effectSummary: "Dyson stage 4: turns on Infinite Power and the grid.",
    special: "megastructure",
  },
  {
    id: "dysonSphereConnect",
    path: 6,
    renderPosition: 10005,
    price: 250000,
    revealThreshold: 200000,
    requires: ["dysonSpherePower"],
    effectSummary: "Dyson stage 5: megastructure capture; Infinite Power remains enabled.",
    special: "megastructure",
  },
  {
    id: "celestialProcessingCoreUnderstanding",
    path: 7,
    renderPosition: 10101,
    price: 50000,
    revealThreshold: 40000,
    requires: ["quantumComputing"],
    effectSummary: "CPC stage 1: +0.5 research-rate field while at its factory star.",
    special: "megastructure",
  },
  {
    id: "celestialProcessingCoreCapabilities",
    path: 7,
    renderPosition: 10102,
    price: 100000,
    revealThreshold: 80000,
    requires: ["celestialProcessingCoreUnderstanding"],
    effectSummary: "CPC stage 2: +1 research-rate field at its factory star.",
    special: "megastructure",
  },
  {
    id: "celestialProcessingCoreDisconnect",
    path: 7,
    renderPosition: 10103,
    price: 150000,
    revealThreshold: 120000,
    requires: ["celestialProcessingCoreCapabilities"],
    effectSummary: "CPC stage 3: grants 0.15 antimatter milestone and permanent antimatter unlock.",
    special: "megastructure",
  },
  {
    id: "celestialProcessingCorePower",
    path: 7,
    renderPosition: 10104,
    price: 200000,
    revealThreshold: 160000,
    requires: ["celestialProcessingCoreDisconnect"],
    effectSummary: "CPC stage 4: +1.5 research-rate field at its factory star.",
    special: "megastructure",
  },
  {
    id: "celestialProcessingCoreConnect",
    path: 7,
    renderPosition: 10105,
    price: 250000,
    revealThreshold: 200000,
    requires: ["celestialProcessingCorePower"],
    effectSummary: "CPC stage 5: +2 at its factory star or +5 outside it; capture.",
    special: "megastructure",
  },
  {
    id: "plasmaForgeUnderstanding",
    path: 8,
    renderPosition: 10201,
    price: 50000,
    revealThreshold: 40000,
    requires: ["neutronCapture"],
    effectSummary: "Forge stage 1: ×1.25 to all resource production rates.",
    special: "megastructure",
  },
  {
    id: "plasmaForgeCapabilities",
    path: 8,
    renderPosition: 10202,
    price: 100000,
    revealThreshold: 80000,
    requires: ["plasmaForgeUnderstanding"],
    effectSummary: "Forge stage 2: ×1.5 to all resource production rates.",
    special: "megastructure",
  },
  {
    id: "plasmaForgeDisconnect",
    path: 8,
    renderPosition: 10203,
    price: 150000,
    revealThreshold: 120000,
    requires: ["plasmaForgeCapabilities"],
    effectSummary:
      "Forge stage 3: grants 0.15 antimatter milestone and permanent antimatter unlock.",
    special: "megastructure",
  },
  {
    id: "plasmaForgePower",
    path: 8,
    renderPosition: 10204,
    price: 200000,
    revealThreshold: 160000,
    requires: ["plasmaForgeDisconnect"],
    effectSummary: "Forge stage 4: ×1.75 to all resource production rates.",
    special: "megastructure",
  },
  {
    id: "plasmaForgeConnect",
    path: 8,
    renderPosition: 10205,
    price: 250000,
    revealThreshold: 200000,
    requires: ["plasmaForgePower"],
    effectSummary:
      "Forge stage 5: ×2 to rates and sets permanent resource-rate bonus; stage multipliers combine to ×6.5625.",
    special: "megastructure",
  },
  {
    id: "galacticMemoryArchiveUnderstanding",
    path: 9,
    renderPosition: 10301,
    price: 50000,
    revealThreshold: 50000,
    requires: ["orbitalConstruction"],
    effectSummary: "Archive stage 1: adds 100,000 capacity to all resources/compounds.",
    special: "megastructure",
  },
  {
    id: "galacticMemoryArchiveCapabilities",
    path: 9,
    renderPosition: 10302,
    price: 100000,
    revealThreshold: 100000,
    requires: ["galacticMemoryArchiveUnderstanding"],
    effectSummary: "Archive stage 2: adds 1,000,000 capacity to all resources/compounds.",
    special: "megastructure",
  },
  {
    id: "galacticMemoryArchiveDisconnect",
    path: 9,
    renderPosition: 10303,
    price: 150000,
    revealThreshold: 150000,
    requires: ["galacticMemoryArchiveCapabilities"],
    effectSummary:
      "Archive stage 3: grants 0.15 antimatter milestone and permanent antimatter unlock.",
    special: "megastructure",
  },
  {
    id: "galacticMemoryArchivePower",
    path: 9,
    renderPosition: 10304,
    price: 200000,
    revealThreshold: 200000,
    requires: ["galacticMemoryArchiveDisconnect"],
    effectSummary: "Archive stage 4: adds 1,000,000,000 capacity to all resources/compounds.",
    special: "megastructure",
  },
  {
    id: "galacticMemoryArchiveConnect",
    path: 9,
    renderPosition: 10305,
    price: 250000,
    revealThreshold: 250000,
    requires: ["galacticMemoryArchivePower"],
    effectSummary:
      "Archive stage 5: adds 10,000,000,000 capacity, sets permanent storage-adder bonus, and captures the structure.",
    special: "megastructure",
  },
] as const satisfies readonly TechnologyDefinition[];

export const TECHNOLOGY_BY_ID = Object.fromEntries(
  TECHNOLOGY_CATALOG.map((technology) => [technology.id, technology]),
) as Readonly<Record<TechId, (typeof TECHNOLOGY_CATALOG)[number]>>;
